### ISSUE TITLE
When cards are reloaded, they sometimes resize to smaller cards, then return to the normal size

### ISSUE THREAD

**Issue by olavblj** [Yalantis/Koloda#102]
I am having a problem using Koloda while fetching data from a Parse.com backend. The first batch of cards shows up fine, but when i load the second batch the first card will sometimes be smaller than it's supposed to. The size will vary from slightly smaller to tiny, and be placed in the upper left corner. The cards will return to the right size after a short while, or when i start dragging. Sometimes the first card is small and the content is small, then the next card is the right size, but with small content, and then the next card is the way it's supposed to be.

I tried overriding the frameForCardAtIndex function so that it always returns the cardsize i want (for testing purposes). This caused the cards to always be the right size, but the content would still shrink and place itself in the upper left corner.

I am not sure whether this is me misunderstanding the framework or if it's a fault in the framework itself, but i have tried anything i can think of, so help would be appriciated.

**Comment by tomekh7** [comment]
I discovered similar issue after application enter from background. My cars are placed in top left corner and are very small. After I swipe they change size and are properly placed. However this happens rarely.

**Comment by czechboy0** [comment]
I've found a way to reliably reproduce it on the Koloda example app, see video for details: https://dl.dropboxusercontent.com/u/14743829/koloda_bg_bug.mov

Steps to reproduce:
1. Drag card to the side, keep it there
2. Press Home button
3. Open app again
4. Card ends up with a completely incorrect frame

**Comment by AEugene** [comment]
Try #108

**Comment by AEugene** [comment]
@czechboy0 the issue you've described fixed with #171
