### ISSUE TITLE
Text inside a Textview of a card-view keeps moving around, shifting in unexpected ways

### ISSUE THREAD

**Issue by terrybu** [Yalantis/Koloda#106]
Hello, thanks for an awesome library. As you see below, I have a textview in this custom card view I made using XIB. The constraints I have are leading and trailing to superview and some vertical spacing from bottom and top, regular stuff. I've noticed that when I start dragging the card view around, the text inside the textview will start shifting. Do you know why this happens? Is it because the textview itself is changing size during the swiping motion? Any fix? Thanks, 

Initial card
![screen shot 2016-01-14 at 5 57 00 pm](https://cloud.githubusercontent.com/assets/7315608/12340392/97ad55f8-bae8-11e5-8a4e-a9ce991e87e6.png)

While swiping
![screen shot 2016-01-14 at 5 57 26 pm](https://cloud.githubusercontent.com/assets/7315608/12340424/d17d754c-bae8-11e5-8437-5cba4a4860f9.png)

**Comment by AEugene** [comment]
@terrybu try #108 , this issue was caused by frame animations of background cards, now it might be fixed.
