### ISSUE TITLE
Better Carthage support

### ISSUE THREAD

**Issue by lightsprint09** [Yalantis/Koloda#107]
The Carthage branch is 48 commits behind. Is this intended?

**Comment by AEugene** [comment]
hi @lightsprint09 . I'm going to combine Carthage and CocoaPods on master branch.

**Comment by kasperwelner** [comment]
Is there any ETA for this? The carthage branch is missing a couple of callbacks that are essential for the app I'm doing, so would be greatly appreciated!

**Comment by grimabe** [comment]
+1

**Comment by AEugene** [comment]
Fixed with #133
