### ISSUE TITLE
Will there be a same repo coming up for Android ??

### ISSUE THREAD

**Issue by iAviatorJose** [Yalantis/Koloda#11]

**Comment by maximletushov** [comment]
Hi, thank you for a question
As I know currently we don't have a plan to implement this component for Android, but definitely it's  possible. @edBaev what do you think ? Thank you.
@iAviatorJose please follow our GitHub and blog https://yalantis.com/blog/
Usually when we implement something new we write a new article.

**Comment by edBaev** [comment]
Hi @iAviatorJose and thank you for your question. unfortunately we don't have any plans for creating this component

**Comment by iAviatorJose** [comment]
@edBaev @maximletushov thank you :)
