### ISSUE TITLE
First card is still appearing as wrong size intermittently

### ISSUE THREAD

**Issue by ghost** [Yalantis/Koloda#111]
This issue was attempted to fix in previous issues but its still appearing. I managed to get a video of the strange resizing here.
https://www.dropbox.com/s/yj8ibqa0n0t8nd7/bug.mov?dl=0

The card is not always the same size, sometimes it could be 1/4 smaller than intended.

**Comment by lunswor** [comment]
I've managed to debug partly this issue but as it happens intermittently it's quite difficult.

I noticed that when Koloda loads the cards it calls `frameForCardAtIndex` the frame it returned for the cards was `(0.0, 0.0, 337.5, 493.0)` but then suddenly it switched and was now `(0.0, -0.0, 208.476479351521, 304.530086874962)`

I have `scalePercent = 1` so `self.frame` seems to be changing somewhere and recalling `frameForCardAtIndex`.

**Comment by AEugene** [comment]
hi @lunswor . Have you tried it on #108 ?

**Comment by lunswor** [comment]
@AEugene I had not seen that. I will give it a go. Thanks

**Comment by wy284086** [comment]
@AEugene i found this bug on ios8.4 ,   on the phone os9 i can't reproduce this bug,  i find this bug causeby layer.transform,   if  i delete  "card.layer.transform"  and add "animateCardsAfterLoadingWithCompletion()"  in kolodaView's function "layoutDeck" ， the bug fixed, so  i guess problem is  layer.transform .  another problem is  could you add view cache in kolodaview ?
