### ISSUE TITLE
Setting corner radius on view returned from viewForCardAtIndex does nothing

### ISSUE THREAD

**Issue by blerchy** [Yalantis/Koloda#112]
I'm trying to set the cornerRadius on a card, but it isn't working intuitively. This is probably due to the fact that the returned view is simply the content view. Any suggestions?

```swift
func koloda(koloda: KolodaView, viewForCardAtIndex index: UInt) -> UIView {
    let view = UIImageView(image: UIImage(named: "sample"))
    view.layer.cornerRadius = 20
    return view
}
```

**Comment by tomekh7** [comment]
Have you tried setting `view.layer.masksToBounds = true`?

**Comment by blerchy** [comment]
This worked! Thank you @tomekh7!
