### ISSUE TITLE
Crash when calling resetCurrentCardNumber() while swiping

### ISSUE THREAD

**Issue by tomekh7** [Yalantis/Koloda#114]
Hi,

first of all thanks for this great work you made to develop Koloda.

I've found the issue in KolodaView. I get crash when `resetCardNumber()` is invoked while swiping cards. I use latest version 2.0.8. I get crash on line 422 of KolodaView.swift :
```self.delegate?.koloda(self, didSwipedCardAtIndex: UInt(self.currentCardNumber - 1), inDirection: direction)```

I have such logic to append new cards. After fetching new bunch of data from server I remove from my array all swiped out records, append new ones and then I invoke `resetCurrentCardNumber()` on KolodaView. I'm sure that the reason of crash is in `UInt(self.currentCardNumber - 1)`. Since I called `resetCurrentCardNumber()` currentCardNumber has 0 value, so creating UInt with negative value goes to crash.

Do you plan to add such features like adding and removing cards using API similar to UITableView?

**Comment by AEugene** [comment]
@tomekh7 We're going to implement similar API, but I'm not sure when we'll have time for it. Similar question asked here #84
