### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by Solum** [Yalantis/Koloda#116]
Hi,

Ever since I upgrade to 2.0.8 I am getting this error and the code wont compile. I have removed Kolada and the references to it in my code and the error disappeared.

I have also posted here: http://stackoverflow.com/questions/35238888/command-failed-due-to-signal-segmentation-fault-11-xcode-7-2

And here's  a Paste Bin of the error: http://pastebin.com/Ff02JYBp

THanks

**Comment by AEugene** [comment]
@Solum try #79

**Comment by terrybu** [comment]
@AEugene ... So renaming the data source/delegate methods should work? Not sure which ones need to be renamed and to what .... would appreciate any details on that

**Comment by terrybu** [comment]
Never mind. Found out that method names really were changed and the OLD method names would throw that segmentation fault 11 error!!

For those of you who still have this problem, make sure you update your KolodaDataSource methods to the following three:

The KolodaViewDataSource protocol has the following methods:

    func koloda(kolodaNumberOfCards koloda:KolodaView) -> UInt
Return the number of items (views) in the KolodaView.

    func koloda(koloda: KolodaView, viewForCardAtIndex index: UInt) -> UIView
Return a view to be displayed at the specified index in the KolodaView.

   func koloda(koloda: KolodaView, viewForCardOverlayAtIndex index: UInt) -> OverlayView?
