### ISSUE TITLE
Implement ability to swipe in any direction

### ISSUE THREAD

**Issue by numen31337** [Yalantis/Koloda#118]
Current implementation allow you to swipe only left/right. For some applications would be helpful to define kinda bit-mask with all directions you are interested in. For example in Tinted app I might be interested to swipe down to instantly start chat or whatever.

**Comment by johncederholm** [comment]
So this is my first time on github, but I modified the koloda files to include a .Up and .Down direction. You can customize what x and y numbers constitute a .Up or .Down (or .Left or .Right direction for that matter). Please let me know if you want them/how I can share them with you.

**Comment by blerchy** [comment]
@johncederholm You might find [this article](https://guides.github.com/activities/contributing-to-open-source/) helpful, scroll down to where it says "Pull Request"

**Comment by felix-dumit** [comment]
I have implemented this over the past couple of days. It's here https://github.com/felix-dumit/Koloda

I will add some more comments and then make a PR soon

**Comment by blerchy** [comment]
@felix-dumit Exciting!

**Comment by johncederholm** [comment]
Thanks @blerchy , but it seems I have been beaten to the punch...

**Comment by Lxrd-AJ** [comment]
@felix-dumit Awesome stuff! When can you make the PR!
