### ISSUE TITLE
Remove background overlay

### ISSUE THREAD

**Issue by ashusath** [Yalantis/Koloda#124]
Hii, will you please let me know how to remove background overlay of cards 

Thank you

**Comment by blerchy** [comment]
What do you mean? Could you provide a screenshot?

**Comment by ashusath** [comment]
sure here it is 
![simulator screen shot 19-feb-2016 11 56 31 am](https://cloud.githubusercontent.com/assets/10862796/13168153/f6cd0032-d6ff-11e5-9958-d9339fb6a56d.png)

**Comment by blerchy** [comment]
But... what do you mean? What are you trying to remove?

**Comment by ashusath** [comment]
in the screenshot it have front card which is at index 0 and in background it display card at index 1, i do not want that next card to be displayed at background

**Comment by AEugene** [comment]
@ashusath There is property for setting count of visible cards. Try this in your viewDidLoad
```swift
        kolodaView?. countOfVisibleCards = 1
```
