### ISSUE TITLE
Last card disappears instead of being animated

### ISSUE THREAD

**Issue by guillosaracco** [Yalantis/Koloda#125]
Hi there!

When integrating Koloda in my project, I noticed that all cards except the last one get animated right or left respectively when calling:

``` swift
@IBAction func leftButtonPressed(sender: UIButton) {
        kolodaView?.swipe(SwipeResultDirection.Left)
}
```

or    

``` swift
@IBAction func rightButtonPressed(sender: UIButton) {
    kolodaView?.swipe(SwipeResultDirection.Right)
}
```

I went back to the example app in this repo, and the same issue occurs.
The last card disappears instead of getting animated left or right.

Is there a work around for this?

Thanks!

**Comment by blerchy** [comment]
This can happen if you're calling something like `kolodaView.resetCurrentCardNumber()` within `kolodaDidRunOutOfCards`. What's happening is that it's performing the reset immediately after the "swipe" action, even though the visual swipe hasn't been completed. My workaround for this was just to perform those functions half a second later:

```swift
let delay = dispatch_time(DISPATCH_TIME_NOW, Int64(NSEC_PER_SEC))
dispatch_after(delay, dispatch_get_main_queue()) {
    // Do some stuff
    self.kolodaView.resetCurrentCardNumber()
}
```

**Comment by guillosaracco** [comment]
Thanks for your response @blerchy 

That makes sense!

**Comment by blerchy** [comment]
I'm glad to have helped. :grin:

**Comment by AEugene** [comment]
@guillosaracco @blerchy  I'm thinking to call kolodaDidRunOutOfCards method in the end of last card animation.

**Comment by serejahh** [comment]
I guess it's better to create an additional delegate method in `DraggableCardDelegate`:

```
func card(card: DraggableCardView, willBeSwipedInDirection direction: SwipeResultDirection) // new one
func card(card: DraggableCardView, wasSwipedInDirection direction: SwipeResultDirection) // old one
```

So 
- when an animation is going to start, we call `willBeSwipedInDirection` and show the next card
- when the animation is finished, we call wasSwipedInDirection and check if koloda is run out

@AEugene, what do you think?

**Comment by AEugene** [comment]
@serejahh It might work out.

**Comment by serejahh** [comment]
Do you have a better solution?
