### ISSUE TITLE
What about toturial?

### ISSUE THREAD

**Issue by shuuchen** [Yalantis/Koloda#126]
Hi Yalantis

I think Koloda is very cool and I like it so much.
Properties, protocols and functions are described, but how to use it in a project is not straightforward.

Would you please provide some tutorials on that? or there already exist?

**Comment by blerchy** [comment]
A good start would be learning about `UITableView` and it's implementation. There are many tutorials for that online. Koloda is very much based off of that kind of implementation, so once you've learned how to use `UITableView` `Koloda` should be second nature. Good luck!

**Comment by AEugene** [comment]
@shuuchen There is 2 examples in root directory and one networking example in branch: https://github.com/Yalantis/Koloda/tree/networking_example
