### ISSUE TITLE
Random white lines appear on the edges of the koloda view

### ISSUE THREAD

**Issue by kellyrose0902** [Yalantis/Koloda#128]
I create white card on a dark background. I noticed sometime (like 1 out of 5) when I drag the card around, there is white line randomly appear on the edge and then disappear

Any help?

**Comment by blerchy** [comment]
+1

I've also had this issue.

**Comment by kellyrose0902** [comment]
I have no idea what cause it, it's a strange pattern, I have 2 buttons for yes and no right underneath the koloda view, and sometime clicking these buttons create the white lines too! This makes no sense, view debugging show nothing either

**Comment by AEugene** [comment]
@blerchy @kellyrose0902 I'll try to debug it. Thanks for noticing the issue.
