### ISSUE TITLE
Dynamically adding card.

### ISSUE THREAD

**Issue by Bashta** [Yalantis/Koloda#129]
Hi! Is there a way to dynamically add cards to Koloda without reloading the whole deck if there is at least 2-3 cards in the deck? Tried a couple of "hacks" but the results are not promising.

**Comment by tomekh7** [comment]
For me the best way is to turn off appearance animation before reloading card stack. Have you tried this approach?

**Comment by Bashta** [comment]
@tomekh7 it works like that but i cant just turn off the animations. i was wondering if there was a more reliable solution for that.

**Comment by AEugene** [comment]
Duplicate #84 . @Bashta @tomekh7 we're working on it.
