### ISSUE TITLE
Trouble running example demo when cloning the repository 

### ISSUE THREAD

**Issue by reneDescartess** [Yalantis/Koloda#134]
Hi, I am trying to just run the demo example but I am having trouble doing it. I have been cloning the repo to my desktop and try running the demo example but I get errors
![screen shot 2016-03-28 at 3 14 51 am](https://cloud.githubusercontent.com/assets/12106896/14076048/444540b2-f493-11e5-97ec-ab6ca193b7b0.png)

**Comment by mytholog** [comment]
perhaps you forgot to run: `$ pod install`
