### ISSUE TITLE
Question: How to allow / disallow swiping of cards?

### ISSUE THREAD

**Issue by gerardo-navarro** [Yalantis/Koloda#135]
Hi Guys,

I'd like to be able to decide whether a card can be swiped or not. I expected to find something, but could not find it in the current version 2.0.10:
`func koloda(koloda: KolodaView, shouldBeSwipedCardAtIndex index: UInt, inDirection direction: SwipeResultDirection) -> Bool`

Do you have some suggestions for how to implement this with the current implementation?

Cheers Gerardo

**Comment by mytholog** [comment]
I'd like to hear about it, too

**Comment by tomekh7** [comment]
One of possible solutions could be disabling/enabling user interactions on kolodaView for particular cards.

**Comment by gerardo-navarro** [comment]
Thanks for the answer. But what if the card is being dragged? I'd like to decide whether it can swiped away completely or not.

**Comment by AEugene** [comment]
@gerardo-navarro That's a good idea! I'll implement it )

**Comment by felix-dumit** [comment]
@AEugene I added this to my PR #131 as I needed to use that in a project, you can extract the relevant part into the code if you'd like.

**Comment by brsunter** [comment]
I would also be interested in preventing the cards from moving at all. Disabling user interaction on the parent view disables it on the child views, which might not be ideal. In my own case I would like to keep the "tapped card" event enabled, but prevent the cards from moving

**Comment by brsunter** [comment]
I needed this for my own project so I opened a pull request. I wanted to preserve user interaction on the card itself and preserve the built in "tapped card" event, but prevent the card from moving at all until certain conditions were met.

https://github.com/Yalantis/Koloda/pull/142
