### ISSUE TITLE
Disable vertical pan

### ISSUE THREAD

**Issue by abraxascorner** [Yalantis/Koloda#137]
I have a koloda view in my table view cell and I want to disable vertical swipe, I would like to have only horizontal swipe. Is there some option for that and can it be done?

**Comment by AEugene** [comment]
Hi @abraxascorner , Koloda doesn't have option to disable horizontal swipe now. You can do it by adjusting delegate methods of gestureRecognizer in DraggableCardView.

**Comment by abraxascorner** [comment]
Thank you. I have changed the code and it worked.

**Comment by rivera-ernesto** [comment]
Could you share your code @abraxascorner ?

**Comment by rivera-ernesto** [comment]
Me, I added this to `DraggableCardView`.

```swift
public override func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
    guard let panRecognizer = gestureRecognizer as? UIPanGestureRecognizer else {
        return super.gestureRecognizerShouldBegin(gestureRecognizer)
    }
    
    // Ensure it's a horizontal drag
    let velocity = panRecognizer.velocity(in: self)
    if abs(velocity.y) > abs(velocity.x) {
        return false
    }
    return true
}

```
