### ISSUE TITLE
Swift Playground Support

### ISSUE THREAD

**Issue by someone29926** [Yalantis/Koloda#140]
Does anyone know whether Koloda should be able to work within Swift playgrounds? Or perhaps, some reason that it would not so I could cut my losses here...

I am learning quickly that playgrounds still have some pretty major kinks to be worked out; nonetheless I have been able to work through many of said kinks already and the potential to aid in designing UIViews more quickly is substantial. Unfortunately Koloda does not seem to be playing ball and as soon as I try to define the view as such:

self.kolodaView = CustomKolodaView(frame: CGRect(x: 0, y: 70, width: 414, height: 590))

I just get errors like: 

![image](https://cloud.githubusercontent.com/assets/1178171/14625054/bf60159e-05ad-11e6-8b15-c764325019fa.png)

I am showing the view in the playground as so:

var ctrl = KolodaViewController()
XCPlaygroundPage.currentPage.liveView=ctrl.view
XCPlaygroundPage.currentPage.needsIndefiniteExecution = true

Any thoughts on this or perhaps someone has a working example to share?

PS I am using the latest Carthage build but as I saw in other issues it may be behind the Cocoapods version - any ideas on whether that might make a difference?

**Comment by AEugene** [comment]
hi @someone29926 could you make quick demo please? I haven't used playgrounds for UI design.

**Comment by AEugene** [comment]
hi @someone29926 . Note that you have to import `pop.xcodeproj`  too, because it’s dependency of Koloda. I was able to render KolodaView with this setup:
<img width="605" alt="screenshot 2016-06-29 17 28 40" src="https://cloud.githubusercontent.com/assets/8107146/16478051/bce1d548-3e9f-11e6-9ccb-eb3b1400bcf6.png">
