### ISSUE TITLE
Change alpha of OverlayView when dragging

### ISSUE THREAD

**Issue by A1exandre** [Yalantis/Koloda#148]
Hi & thanks for this :)

I'm using Koloda with an OverlayView that colors the card in red/green depending on the direction and display "Yes!", "No!" depending on the direction.

The issue I have is that Koloda increases the alpha of the OverlayView too slowly. As a result, my "Yes" / "No" label that is on the Overlayview starts being barely visible only when the card is already dragged almost to the border of the screen. 

I haven't found any settings to tweak the alpha of OverlayView at the beginning/end of dragging. Could it be possible to add something for this issue?

Thanks!

**Comment by tomekh7** [comment]
I've just created PR that cover the issue [https://github.com/Yalantis/Koloda/pull/150](url) Feel free to comment if this will be usable for you.

**Comment by AndrewiOS** [comment]
Hi @A1exandre, we've added the function for your convenience

**Comment by AndrewiOS** [comment]
Hi @A1exandre, we've added the function for your convenience. 
    public func updateWithProgress(percentage: CGFloat) {
        overlayStrength = percentage
    }

you can override it and do what you want. 
For example in your CustomOverlayView class appears quicker than it does this by default 

class CustomOverlayView: OverlayView {
    
    override func updateWithProgress(percentage: CGFloat) {
        alpha = percentage * 3
    }
    
}
