### ISSUE TITLE
Change Autolayout when using more than one xib 

### ISSUE THREAD

**Issue by pretu** [Yalantis/Koloda#151]
Hi,
First of all, thanks to the great library work yalantis.Am using this,and i have  issues is that koloda using more than one xibs to display the cards.Multiple Xibs are shown in simulator but the constraints are not fit into koloda's exact view size in the simulator.How to adjust the view size any solution for me please?

Thanks!

**Comment by AndrewiOS** [comment]
@pretu Thank you for your question. We'll consider it

**Comment by AEugene** [comment]
hi @pretu could you give us an example project?

**Comment by pretu** [comment]
Hi,
    Good Eve,this is the reference of my example project.
dropbox.com/s/xaldxxwnbn1gocp/Koloda-ObjC-master%202.zip?dl=0
<https://www.dropbox.com/s/xaldxxwnbn1gocp/Koloda-ObjC-master%202.zip?dl=0>,please
check and give me solution for me.

Regards
Preetha P.

                            Thank you.

**Comment by AEugene** [comment]
hi @pretu. Current version of Koloda doesn’t support Objective-C. You’re using library provided by another author, you should move this issue to his repository.
