### ISSUE TITLE
Remove current card after swipe

### ISSUE THREAD

**Issue by maximeloizeau** [Yalantis/Koloda#159]
Hi,

I am currently trying to remove each card after it has been swiped but I have an issue with the indexes after some point (out of bounds).
The index used by Koloda continues to increment whereas my array is being shrinking. If I remove the first item each time, the current index should be 0 right ?

It seems to work if I reset the currentindex each time but it reloads the view and I'm looking to do it discretly.

Here is how I remove the item: 

```
self.suggestions.removeAtIndex(index)
self.cardView.removeCardInIndexRange(index...index, animated: true)
```

suggestions is my datasource array and index is the index given in didSwipeCardAtIndex.

So if you have any leads for me, thanks.

**Comment by AEugene** [comment]
hi @maximeloizeau . I'll investigate the issue.

**Comment by serejahh** [comment]
Hi @maximeloizeau! Could you check the issue in the latest Koloda version? We've fixed several bugs with `out of bounds`

**Comment by serejahh** [comment]
Btw, what's the purpose of the action? To prevent reverting cards?

**Comment by maximeloizeau** [comment]
Hi,
The goal of this was to forget a card after it has been swiped. I am doing an infinite swipe and I don't want to see the same card another time.

I will see when I can test the new version, thanks for the update. I think I found an alternative solution for it to work in the meantime.

**Comment by serejahh** [comment]
Thanks for the response, I got your. Please let me know if the issue is still exists
