### ISSUE TITLE
Swipe right to see previous card

### ISSUE THREAD

**Issue by lamelas** [Yalantis/Koloda#161]
How can I use a swipe right to show me the previous card in the stack? I tried this but because it's only called after the swipe, I get the same card I just swiped.

```
   func koloda(koloda: KolodaView, didSwipeCardAtIndex index: UInt, inDirection direction: SwipeResultDirection) {
        if(direction == .Right) {
            koloda.revertAction()
        }
    }
```
Can we get a willSwipeCardAtIndex or something like that to be able to revert the action before the swipe happens?

**Comment by lamelas** [comment]
I can get it to work by editing the revertAction method and doing
currentCardIndex -= 2
instead of
currentCardIndex -= 1

But I feel dirty... :)

**Comment by lamelas** [comment]
Eventually gave up on this since it would break the card stack paradigm (if you're throwing cards out, you can't go back).

If anyone's curious, I got an action that pushes the previous card into the top of the stack. Koloda didn't do it out of the box so after changing the visilibity of some methods, managed to do it like this:

1. Save the current card index
2. Clear the view
3. Change current card index to the previous one
4. Use the `createCardAtIndex` method to get the views for the cards I want to animate (the previous one and the currently visible). The previous one is created with a frame outside the view but the others with their exact same position.
5. Adding those subviews to Koloda (which is currently empty because of number 2)
6. Animate them into view (so the card that started with `frameForCardAtIndex(0)` is animated with target `frameForCardAtIndex(1)`, etc).
7. When the cards are finished animating into their places, `reloadData()`and koloda reappears with the previous card on top.

Not the best solution but it works.

**Comment by techmehra** [comment]
How can implement that
