### ISSUE TITLE
Override swipe rotation

### ISSUE THREAD

**Issue by lbatteau** [Yalantis/Koloda#163]
Is it possible to prevent the cards from rotating when swiping? I looked into it, but can't find a way without having to subclass everything. I would like to just have translation. If not I'll issue a feature request.

**Comment by AEugene** [comment]
hi @lbatteau . Currently Koloda doesn't support it.

**Comment by vvit** [comment]
@lbatteau have you tried this?

```
kolodaView.rotationAngle = 0
kolodaView.delegate = self
kolodaView.dataSource = self
```
