### ISSUE TITLE
App crash due to 'Could not load NIB in bundle:' with name 'OverlayView''

### ISSUE THREAD

**Issue by kshrikant** [Yalantis/Koloda#165]
Hi @AEugene Im developing sample app. Here is my code.

	import UIKit
	import Koloda
	import pop

	class ViewController: UIViewController, KolodaViewDataSource,     KolodaViewDelegate 
	{

		private var numberOfCards: UInt = 5

		@IBOutlet weak var kolodaView: KolodaView!
	
		var images : [UIImage] = [UIImage(named : "temp1.jpg")!,UIImage(named : "temp2.jpg")!,UIImage(named : "temp3.jpg")!]
	
		override func viewDidLoad() {
			super.viewDidLoad()
		
			kolodaView.dataSource = self
			kolodaView.delegate = self
		
			// Do any additional setup after loading the view, typically from a nib.
		}

		override func didReceiveMemoryWarning() {
			super.didReceiveMemoryWarning()
			// Dispose of any resources that can be recreated.
		}
	
		//MARK: KolodaViewDataSource
	
	
		func kolodaNumberOfCards(koloda:KolodaView) -> UInt
		{
			return numberOfCards
		}
	
		func koloda(koloda: KolodaView, viewForCardAtIndex index: UInt) -> UIView
		{
			return UIImageView(image: images[Int(index)])
		}
	
		func koloda(koloda: KolodaView, viewForCardOverlayAtIndex index: UInt) -> OverlayView? {
			return NSBundle.mainBundle().loadNibNamed("OverlayView",
													  owner: self, options: nil)[0] as? OverlayView
		}

	
		//MARK: KolodaViewDelegate
	
		func kolodaDidSwipedCardAtIndex(koloda: KolodaView, index: UInt,  direction: SwipeResultDirection) {
			//Example: loading more cards
			if index >= 3
			{
				numberOfCards = 6
				kolodaView.reloadData()
			}
		}
	
		func kolodaDidRunOutOfCards(koloda: KolodaView)
		{
			//Example: reloading
	//        kolodaView.resetCurrentCardNumber()
			kolodaView.resetCurrentCardIndex()
		}
	
		func kolodaDidSelectCardAtIndex(koloda: KolodaView, index: UInt) {
			UIApplication.sharedApplication().openURL(NSURL(string: "http://yalantis.com/")!)
		}
	
		func kolodaShouldApplyAppearAnimation(koloda: KolodaView) -> Bool {
			return true
		}
	
		func kolodaShouldMoveBackgroundCard(koloda: KolodaView) -> Bool {
			return true
		}
	
		func kolodaShouldTransparentizeNextCard(koloda: KolodaView) -> Bool {
			return true
		}
	
		func kolodaBackgroundCardAnimation(koloda: KolodaView) -> POPPropertyAnimation? {
			return nil
		}

	}

and my pod file is

       pod 'Koloda', '~> 3.1.1'

and when i run the app it says 

      *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', 
      reason: 'Could not load NIB in bundle:  'NSBundle  (loaded)' with name 'OverlayView'' 

Can u tell me whats the issue ?

**Comment by AEugene** [comment]
hi @kshrikant . `OverlayView` class provided in Koloda doesn't have nib. You should implement own subclass of `OverlayView` with Nib. Take a look at Example project.

**Comment by kshrikant** [comment]
@AEugene Ok thanks.

**Comment by wixvii** [comment]
@AEugene hey, How can I connect overlayImageView to overlayview when using pod ?
