### ISSUE TITLE
First card frame is wrong when quick swipe

### ISSUE THREAD

**Issue by ThaoPN** [Yalantis/Koloda#167]
With 100 card, when I swipe very quickly. Some time the first card frame is wrong. You can only reproduce it on device.

[![https://gyazo.com/5f4a7c748aecc6b3598210445254a82e](https://i.gyazo.com/5f4a7c748aecc6b3598210445254a82e.jpg)](https://gyazo.com/5f4a7c748aecc6b3598210445254a82e)
[![https://gyazo.com/9b0da50506729b09e3afb3f3523d1529](https://i.gyazo.com/9b0da50506729b09e3afb3f3523d1529.jpg)](https://gyazo.com/9b0da50506729b09e3afb3f3523d1529)
[![https://gyazo.com/dbd4919254d699f698495284ff8ceaee](https://i.gyazo.com/dbd4919254d699f698495284ff8ceaee.jpg)](https://gyazo.com/dbd4919254d699f698495284ff8ceaee)

**Comment by ThaoPN** [comment]
I have 2 screen recording.
https://youtu.be/XMP6kCsqiZM
https://youtu.be/vv6p4TJxhUA

**Comment by glennposadas** [comment]
have you guys solve this? I'm just afraid that I might encounter this bug in the future, hopefully not.

**Comment by rmorbach** [comment]
I'm facing the same bug. After swiping about 4 cards, the front card frame became wrong.

**Comment by charlesmarino1** [comment]
I have had this issue as well

**Comment by mzgnr** [comment]
is this bug fixed ?

**Comment by freaqed** [comment]
Hi guys!
The issue seems to be fixed in latest version of component.
Let us know if anyone swill facing that.
