### ISSUE TITLE
How can I add a visible view below the UIImage?

### ISSUE THREAD

**Issue by jgutierrez11** [Yalantis/Koloda#168]
Hi, I am trying to use this library with an UIImage at top and a UIView at bottom with two UILabels inside.
But the bottom view must be visible before dragging the main view.
Does anyone has a recipe to accomplish this? I would really appreciate your help.

|                                 |
|       UIImageView     |
|                                 |
 - - - - - - - - - - - - - - - -
|    UILabel                 |
|    UILabel                 |
| - - - - - - - - - -   - - - - |

Thanks!

**Comment by AEugene** [comment]
hi @jgutierrez11 . I can't understand the problem. Could you add more details?

**Comment by serejahh** [comment]
Hi @jgutierrez11 

Please describe how you create the main card view
