### ISSUE TITLE
Problem with override CustomOverlayView 

### ISSUE THREAD

**Issue by Sfresneda** [Yalantis/Koloda#169]
I have a little problem trying to implement CustomOverlayView.

I import the repo with pods and all is functional, but i need to comment this lines, because i receive a error and I don’t know why:

    override var overlayState: SwipeResultDirection? {
        didSet {
            switch overlayState {
            case .Left? :
                overlayImageView.image = UIImage(named: overlayLeftImageName)
            case .Right? :
                overlayImageView.image = UIImage(named: overlayRightImageName)
            default:
                overlayImageView.image = nil
            }
        }
    }

The error on Override: "Property 'overlayState' with type 'SwipeResultDirection?' Cannot override a property with type 'OverlayState'"

The rest of the code is functional 100%.

**Comment by AEugene** [comment]
hi @Sfresneda . Could you give an example project? I can’t reproduce your issue with code in master.
