### ISSUE TITLE
Use Int instead of UInt

### ISSUE THREAD

**Issue by clayellis** [Yalantis/Koloda#170]
All instances of `UInt` on public facing methods should be changed to `Int`s. 
`UInt` doesn't work when indexing into an array. `Int` does.
The DataSource pattern relies heavily on `Array`s and indexing.
This is reason enough to make this change.

**Comment by AEugene** [comment]
Hi @clayellis . You’re totally right! I want to made more friendly API in next version of Koloda for Swift 3.
