### ISSUE TITLE
Example project won't compile

### ISSUE THREAD

**Issue by sarunw** [Yalantis/Koloda#173]
In BackgroundAnimationViewController

Line 27: kolodaView.countOfVisibleCards = kolodaCountOfVisibleCards

There is not property `countOfVisibleCards` in `CustomKolodaView`

**Comment by ayvazj** [comment]
Depending on which revision of the code you're using it might have been renamed to `kolodaView.countOfVisibleCards = kolodaCountOfVisibleCards`

**Comment by Roman-Scherbakov** [comment]
Fixed with #176
