### ISSUE TITLE
Change default swipe to Top and Bottom instead of Left and Right

### ISSUE THREAD

**Issue by srinadh588** [Yalantis/Koloda#175]
Hi, Kolada default swipe supporting left and right swipes. i need to do top and bottom and not allow to swipe left and right. is there any possibility to restrict it.

**Comment by lamelas** [comment]
You can implement this method in your delegate: 
` func koloda(koloda: KolodaView, allowedDirectionsForIndex index: UInt) -> [SwipeResultDirection]`
and just return an array with `.Up` and `.Down`

**Comment by BMR731** [comment]
if i need to do top , bottom ,left ,right ,what should i do? ,i use 
`func koloda(koloda: KolodaView, allowedDirectionsForIndex index: UInt) -> [SwipeResultDirection]
 return [.Left, .Right, .Down, .Up]

    func koloda(koloda: KolodaView, shouldSwipeCardAtIndex index: UInt, inDirection direction: SwipeResultDirection) -> Bool {
        print(direction.hashValue)
        
        if direction == SwipeResultDirection.Up{
            return true
        }
        if direction == SwipeResultDirection.Left{
           return true

        }
        if direction == SwipeResultDirection.Down{
            print("up pass")
            return true
        }
        if direction == SwipeResultDirection.Right{
            return true 
        }
        return false
    }


`
but it when i debug in the function below
`
    func koloda(koloda: KolodaView, didSwipeCardAtIndex index: UInt, inDirection direction: SwipeResultDirection) {
        if direction == SwipeResultDirection.Up{ //i set breakpoint here, the direction is <invalid> type
            debugPrint("listen up")
        }

        if direction == SwipeResultDirection.Left{ // set breakpoint here, the direction is .Left type,????,how
            debugPrint("listen left")
        }
        
        if direction == SwipeResultDirection.Right{
            debugPrint("listen right")
        }
        if direction == SwipeResultDirection.Down{
            debugPrint("listen down")
        }
    }
`

so if i want to do some works on four directions, what should i do ..,thank you
