### ISSUE TITLE
kolodaBackgroundCardAnimation is mandatory

### ISSUE THREAD

**Issue by carbocation** [Yalantis/Koloda#18]
If `kolodaBackgroundCardAnimation` is not implemented, building fails and Xcode complains about your controller not conforming to the KolodaViewDelegate protocol. However, the docs claim that this method is optional: "This method is fired on swipping, when any cards are displayed. ***If you don't return frame animation, or don't implement it, the koloda will apply default animation.***"

Should this be marked optional, or is it mandatory?

**Comment by AEugene** [comment]
It's error in readme. We'll update it. Currently swift doesn't provide way to make protocol methods optional without "@objc" declaration. We will implement these methods as optional, when swift 2.0 is  released.
