### ISSUE TITLE
How can I update the Koloda View image using a Backendless image url?

### ISSUE THREAD

**Issue by brandon-hardy** [Yalantis/Koloda#180]
At the moment the application uses images from the assets folder in Xcode.
I want to be able to use images that are stored within the backendless database as URL Strings.

![zk5m4](https://cloud.githubusercontent.com/assets/20564993/17078464/9344ad56-50eb-11e6-99d5-d0d080e29f4d.png)

The code currently in the project which displays the Koloda view is as follows:

![1e015aea90278746fac1a3b6d268ec2b](https://cloud.githubusercontent.com/assets/20564993/17078468/d886845c-50eb-11e6-8e97-5d095c98702a.png)

Research from previous Stack questions brought up the following: http://stackoverflow.com/questions/36966110/add-remove-dynamically-koloda-views

However, the user uses his own personal database to retrieve images.

I would like to retrieve the URL from Backendless and turn this into an image to put onto the UIImageView & Show the next user when swiped either way.

**Comment by serejahh** [comment]
Hi @brandon-hardy

The idea is similar to UITableViewCell. How would you download images from Backendless? I believe you would use SDWebImage or some swift implementation. Implementation could look like:
``` swift
func koloda(koloda: KolodaView, viewForCardAtIndex index: UInt) -> UIView {
    let imageView = UIImageView()
    imageView.sd_setImageWithURL(url, placeholderImage: placeholder)
    return imageView
}
```
