### ISSUE TITLE
Error in removeCardAtIndexRange

### ISSUE THREAD

**Issue by martolini** [Yalantis/Koloda#182]
Line 635 through 639 of `KolodaView.swift`

```
let currentItemsCount = countOfCards
let visibleIndexes = [Int](indexRange).filter { $0 >= currentCardIndex && $0 < currentCardIndex + countOfVisibleCards }
if !visibleIndexes.isEmpty {
    proceedDeletionInRange(visibleIndexes[0]..<visibleIndexes[visibleIndexes.count])
}
```

Unless I'm mistaken, when I send in `indexRange = 0...0`, `visibleIndexes[visibleIndexes.count]` will always throw an `Index out of range` error.

Changing it to `proceedDeletionInRange(visibleIndexes[0]...visibleIndexes[visibleIndexes.count - 1])` should fix the issue.

**Comment by freaqed** [comment]
Hey @martolini!
Current version of `KolodaView` requires `indexRange` parameter to be `CountableRange`, so it's no longer possible to pass `0...0`. If you try to pass something like `0..<0` nothing will happened.

Sorry for delay in answering that, and thanks for contribution!
