### ISSUE TITLE
kolodaSwipeThresholdRatioMargin has no effect

### ISSUE THREAD

**Issue by nilshott** [Yalantis/Koloda#183]
As far as I understand the documentation, this code should trigger a swipe, when a card is dragged more then 30% towards the screen edge:

```
public func kolodaSwipeThresholdRatioMargin(koloda: KolodaView) -> CGFloat? {
	return 30.0
}
```

The function gets called, but the threshold seems to be stuck at 50%.

**Comment by AEugene** [comment]
Hi @nilshott . This is ratio, so if you want 30% you should return `0.3` and also it depends on `KolodaView`  size rather not screen size.

**Comment by nilshott** [comment]
Thanks!
