### ISSUE TITLE
2 Extra KoladaViews

### ISSUE THREAD

**Issue by mrigdon** [Yalantis/Koloda#186]
Seems `kolodaNumberOfCards` is returning 2 too many views. When I test
```swift
func kolodaNumberOfCards(koloda: KolodaView) -> UInt {
    return 3
}
```
I can swipe 5, and when I test
```swift
func kolodaNumberOfCards(koloda: KolodaView) -> UInt {
    return 5
}
```
I can swipe 7. What could be causing this?

**Comment by AEugene** [comment]
@mrigdon are you sure that you don't use `insertCardAtIndexRange` somewhere? I can't reproduce this issue on latest version.

**Comment by mrigdon** [comment]
Pretty sure the problem came from setting the number of visible cards before setting the delegate and dataSource. Anyhow, just fixed it so I'll close.
