### ISSUE TITLE
Wrong positioning in case viewForCardAtIndex loaded through storyboard 

### ISSUE THREAD

**Issue by Daemon-Devarshi** [Yalantis/Koloda#191]
I loaded `viewForCardAtIndex` through xib using below code and it showed button and label added on UI at correct positions:

```
func koloda(koloda: KolodaView, viewForCardAtIndex index: UInt) -> UIView {
        return NSBundle.mainBundle().loadNibNamed("ContentView",
                                                  owner: self, options: nil)[0] as! UIView
}
```

But when I loaded it through storyboard using below code, it showed button and label at wrong positions:

```
func koloda(koloda: KolodaView, viewForCardAtIndex index: UInt) -> UIView {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let contentViewController = storyboard.instantiateViewControllerWithIdentifier("ContentViewController") as! ContentViewController
        return contentViewController.view
}
```

Here is reference image:

<img width="599" alt="xib vs storyboard viewforcardatindex" src="https://cloud.githubusercontent.com/assets/959126/17543236/ba9f0978-5eec-11e6-8efe-2e490113c584.png">

Any ideas on what is going wrong over here?

**Comment by serejahh** [comment]
Hi @Daemon-Devarshi! Could you provide a test project? Then I can investigate the issue

**Comment by Teglgaard** [comment]
I am having the same issue. If @Daemon-Devarshi will not provide a test project i can try to make one soon. Please let me know if it is needed.

**Comment by freaqed** [comment]
@Teglgaard, @Daemon-Devarshi if anyone of you still facing the issue please share some code/example. Can't really help without more information

**Comment by Teglgaard** [comment]
I believe my team found a way around it somehow, but I have no longer any idea. I would have loved to help now but nearly half a year has passed. Sry

**Comment by freaqed** [comment]
Ok, I bet the issue related to constraints stuff. You can fix it using container view, instead of root view of your ViewController. In case @Daemon-Devarshi still have the issue - reopen and let me know

**Comment by ethan021021** [comment]
Any update on this? Having this same exact issue currently.
