### ISSUE TITLE
Add swipe directions and change the swipe actions

### ISSUE THREAD

**Issue by taktikal17** [Yalantis/Koloda#192]
Hi,

Thank you for the repository! I want to know how I can add changes.

When I swipe left, I would like the card to be send at the end of the deck.
Delete the swipe right.
Add a swipe down, to close the swipe view.

Do you see what guidelines I can use to do it?

Thank you a lot!

Best!

**Comment by serejahh** [comment]
Hi @taktikal17. Thanks for using our component! 

1. Conform `KolodaViewDelegate` protocol
2. Implement the method: `func koloda(koloda: KolodaView, didSwipeCardAtIndex index: UInt, inDirection direction: SwipeResultDirection)`
3. Add your custom action (switching through `direction` cases)

**Comment by MacMeDan** [comment]
This would be nice on the `ReadMe` so people can easily execute actions based on swipe direction. 

![bitmoji](https://render.bitstrips.com/v2/cpanel/7834193-218147167_28-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by MacMeDan** [comment]
Also just as informational. If you are using the index property to find your image the index is `1` based where your array is `0` based. So remember to `-1` to get the correct image.
