### ISSUE TITLE
ERRORs while installing using pod 

### ISSUE THREAD

**Issue by DineshKachhot** [Yalantis/Koloda#193]
Using pod and got this error while build.....

"Include of non-modular header inside framework module 'pop.POP' "

**Comment by mediatainment** [comment]
same problem here with carthage

**Comment by serejahh** [comment]
Hi guys. Could you specify your cocoapods version and add content of podfile?

**Comment by serejahh** [comment]
@mediatainment please check out [a demo project with carthage](https://github.com/serejahh/Koloda-Carthage-usage). I hope it'll help yout

**Comment by serejahh** [comment]
@DineshKachhot did you add `use_frameworks!` to your podfile?

**Comment by Aiwis** [comment]
Hello,

I had the same issue and realized I still hadn't updated cocoapods to 1.*. 

Hope it can help :)

**Comment by tredds** [comment]
post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end

**Comment by freaqed** [comment]
Please update the library to a new version. It should fix any issues related to pods.
