### ISSUE TITLE
How to create a flashcard like app?

### ISSUE THREAD

**Issue by brightfuture** [Yalantis/Koloda#194]
I'm trying to create a flashcard app with Koloda, which displays an image in the front, and when user taps it, it shows the back. 
I found it quite hard to return 2 image views for each card at index and animating between them, can we make it possible for each draggable card to contain multiple views, which are show at different time?

**Comment by serejahh** [comment]
Hi @brightfuture. Thanks for the interest.

Yes, it's a quite complex task. I guess, you can create a subclass of `DraggableCardView`, override `func tapRecognized(recogznier: UITapGestureRecognizer)` and then add your behavior
