### ISSUE TITLE
Catch a card while it's reverting 

### ISSUE THREAD

**Issue by serejahh** [Yalantis/Koloda#201]
Steps:
1. Swipe several cards
2. Press revert action button
3. Catch the card while it's reverting 

Actual result: a card becomes transparent
![photo 23-08-16 10 43 54](https://cloud.githubusercontent.com/assets/2575555/17884091/fae663fa-691e-11e6-8ffd-da62cf52daf3.png)
Expected result: 
![photo 23-08-16 10 44 04](https://cloud.githubusercontent.com/assets/2575555/17884092/fae75fda-691e-11e6-9d71-4d47120bcf90.png)

**Comment by SatoshiN21** [comment]
@serejahh
 Its bug in Koloda's default animation class "KolodaViewAnimator" probably.
when you catch the card, revert alpha animation is cancelled in somewhere.
