### ISSUE TITLE
Error after pull with Cocopods

### ISSUE THREAD

**Issue by trollblocks** [Yalantis/Koloda#203]
Hello I'm trying to test the exemple project but after a few try a have some errors .

in KoladaView.swift   
-visibleCards.removeLast(cards.count)          Argument passed to call that takes no arguments

and in DraggableCardView.swift

  panGestureRecognizer = UIPanGestureRecognizer(target: self, action: ,#selector(DraggableCardView.panGestureRecognized(_:)))

 Expected expression in list of expressions

how did you fix it . 

I Use Xcode 7.2 with the latest Cocopods Version.

**Comment by serejahh** [comment]
Hi @trollblocks 

Thanks for the descriptive report. You use xcode 7.2 with swift 2.1, but the component is written in swift 2.2 (it's also mentioned in readme). So you have two options

1. Update your project to Xcode 7.3 and use swift 2.2
2. Use an old version of Koloda when it was compatible with Xcode 7.3
