### ISSUE TITLE
Manage swipe animation duration ?

### ISSUE THREAD

**Issue by snahedis** [Yalantis/Koloda#205]
Hi, 

First thanks for the great work !

I was wondering if there is a way to manage the swipe animation duration ? 
I've seen the cardSwipeActionAnimationDuration but it's a constant. Have I missed something ?

I guess I could override the swipe function but is there a simpler way to change the animation speed ?

Thanks again :)

**Comment by serejahh** [comment]
Hi @snahedis! 

Your question is related to #204 a bit. For now it's not possible, but I guess I can add a method to delegate.

**Comment by snahedis** [comment]
Ok, thanks @serejahh :)

**Comment by popaaaandrei** [comment]
Pls, that would be wonderful :) 👍

**Comment by dylangwight** [comment]
@serejahh I would love this too
