### ISSUE TITLE
How to change the sliding direction

### ISSUE THREAD

**Issue by SomnusDN** [Yalantis/Koloda#208]
I want to realize sliding up and down,left and right sliding bounce back

**Comment by serejahh** [comment]
Hi @SomnusDN!

You can set any allowed direction. Use a delegate method: `func koloda(_ koloda: KolodaView, allowedDirectionsForIndex index: Int) -> [SwipeResultDirection]`. Just return [.Up, .Down]

**Comment by SomnusDN** [comment]
Thank you，problem solved.And I have a new problem，how to get the current card position？

发自我的 iPhone
