### ISSUE TITLE
Swift 3: Subclassing / Configuring

### ISSUE THREAD

**Issue by lukas2** [Yalantis/Koloda#209]
Hello, 

the swift-3 branch is fine to run Koloda. But because the class and accessible methods are marked "public" and not "open" we cannot subclass or override KolodaView.swift.

Background: We currently subclass and override `frameForCardAtIndex(_ index: UInt) -> CGRect` because we want to calculate our own frame. 

I would like to help to fix this, but haven't decided which way to do it is best.

Idea 1: Turn everything `public` into `open`, so subclassing is no problem.
Idea 2: Make only `frameForCardAtIndex(_ index: UInt) -> CGRect` and the class `open`, so that subclassing for configuration is possible.
Idea 3: Make method a for calculating frame injectable/configurable by exposing it via optional KolodaViewDelegate function. (if not implemented, use the default function.)

I currently favor #2 and will write it into our fork, but I would like to submit a pull request that works for everyone if possible.

**Comment by lukas2** [comment]
Here's how #2 could look like: https://github.com/lukas2/Koloda/commit/39aec58082fc0cd60d15464579471bd9d8a420f0

**Comment by fantoine** [comment]
+1 for #2

**Comment by fantoine** [comment]
Also, it could be good to merge master changes to swift 3 branch

**Comment by lukas2** [comment]
I've created a PR to master. Hm. Perhaps it should be merged into swift-3 branch first?

**Comment by alibasta** [comment]
+1

**Comment by lukas2** [comment]
Updated PR.

**Comment by serejahh** [comment]
https://github.com/Yalantis/Koloda/pull/219 is merged
