### ISSUE TITLE
reloadData doesn't refresh card deck after swipe

### ISSUE THREAD

**Issue by yaelirub** [Yalantis/Koloda#213]
When we're calling reloadData without swiping, the currentCardIndex is 0 which gets clear() to be called in reloadData() and so visibleCards isEmpty which then get setupDeck(),layoutDeck() and applyAppearAnimationIfNeeded() to be called. 
after Swipe though, the currentCardIndex is not 0 ,and those methods are not being called in reloadData, hence the deck is not refreshed. How can we get the deck to reload?

 public func reloadData() {
        guard let numberOfCards = dataSource?.kolodaNumberOfCards(self) where numberOfCards > 0 else {
            clear()
            return
        }

```
    if currentCardIndex == 0 {
        clear()
    }

    countOfCards = Int(numberOfCards)
    if countOfCards - (currentCardIndex + visibleCards.count) > 0 {
        if !visibleCards.isEmpty {
            let missingCards = missingCardsCount()
            loadMissingCards(missingCards)
        } else {
            setupDeck()
            layoutDeck()
            applyAppearAnimationIfNeeded()
        }
    } else {
        reconfigureCards()
    }
}
```

**Comment by niazoff** [comment]
I'm trying to reloadData and it's not working regardless which index I'm at. Is this part of the same bug?

**Comment by niazoff** [comment]
Never mind, I meant to be using resetCurrentCardIndex().

**Comment by yaelirub** [comment]
Any news about this bug?

**Comment by darkandchoco** [comment]
use reloadCardsInIndexRange(_ indexRange: CountableRange<Int>) instead, this will reload the cards even if current card index != 0

**Comment by sandeepbol** [comment]
@darkandchoco This also didn't work for me. I tried doing

        koloda.reloadCardsInIndexRange(0 ..< count)
