### ISSUE TITLE
Swift Compiler Error: Xcode 8 GM

### ISSUE THREAD

**Issue by Jamongkad** [Yalantis/Koloda#216]
<img width="435" alt="screen shot 2016-09-21 at 6 33 37 pm" src="https://cloud.githubusercontent.com/assets/21994/18707767/0f744860-802a-11e6-9bec-842a17371dc4.png">

I get a whole bunch of compiler errors when using Koloda (3.1.2)

**Comment by JustinM1** [comment]
did you install using cocoapods? They still haven't merged the swift 3 branch into the master so you will need to install the pod pointing to the swift 3 branch. 

pod 'Koloda', :git => 'https://github.com/Yalantis/Koloda.git', :branch => 'swift-3'

Also, in general, upgrading to the newest version of cocoapods will help with swift 3 pods.

sudo gem install cocoapods --pre

**Comment by Jamongkad** [comment]
Wonderful it built cleanly! In my case I was already using the latest Cocoapods but it was pointing to the swift-3 branch that solved the problem.

**Comment by matybrennan** [comment]
It was working well on the swift 2.2 version but when upgraded to the 3.0 branch I had issues with my datasource and delegate being alloc to the same part of memory. Screenshot is attached to show issue. Any reasons to why this is happening?
![screen shot 2016-11-07 at 1 23 42 pm](https://cloud.githubusercontent.com/assets/12101727/20044598/3fd420dc-a4ee-11e6-9997-4626767d8c84.png)
