### ISSUE TITLE
Argument type 'Range<Int>' does not conform to expected type 'Sequence'

### ISSUE THREAD

**Issue by stefanMertens** [Yalantis/Koloda#217]
After converting my code to Swift 3.0, I got a bunch of errors. I was able to eliminate most of those, but there are 5 errors remaining. All of these are in the KolodaView.swift file and all of them say the same thing: "Argument type 'Range<Int>' does not conform to expected type 'Sequence'". I attached a screenshot of these errors.

![screenshot errors](https://cloud.githubusercontent.com/assets/12742063/18709980/1a025910-8003-11e6-8583-165a2a188373.png)

Anyone an idea how to fix this? Thanks in advance!

**Comment by stefanMertens** [comment]
After a bunch of different steps (clean, rebuild, ...) these errors have disappeared. This issue may be considered closed.

**Comment by aiyub007** [comment]
I am having same problem. But Clean build not working.
