### ISSUE TITLE
OverlayView should be open class in swift-3  

### ISSUE THREAD

**Issue by shtalhaejaz** [Yalantis/Koloda#220]
Hi,

I am facing following syntax errors. I am using swift-3 branch in my pods.I want to subclass OverlayView. OverlayView is public class.Please make it open so that anyone can customise it.Please fix the following issues as soon as possible.

Regards,
Talha Ejaz

![screen shot 2016-09-26 at 4 37 35 pm](https://cloud.githubusercontent.com/assets/14291940/18832939/983eecfa-8407-11e6-86cf-f1f419367f7f.png

**Comment by treyhakanson** [comment]
Was just about to post about this issue. Please mark OverlayState open as well.

**Comment by serejahh** [comment]
It should be done #219

**Comment by shtalhaejaz** [comment]
OverlaView is not updated yet in new version 3.1.2. Please update it as open class as well.

**Comment by Jaro22** [comment]
This should be reopened. OverlayView and OverlayState are still *not* fixed after #219

**Comment by serejahh** [comment]
I've pushed the changes: https://github.com/Yalantis/Koloda/commit/eea23944361a124b0502043718be50f13a53e9f2#diff-debaeb920b75c77b4cb4a04388fdce81R11

API is changed so it's gonna be `4.0` soon
