### ISSUE TITLE
Swift 3 - Example needs to be updated to Swift 3

### ISSUE THREAD

**Issue by zakarykinnaird84** [Yalantis/Koloda#221]
# Report

> In Swift 3 Branch

⚠️ Example project in Swift 3 to work on Xcode 8.

**Comment by serejahh** [comment]
Example app in `swift-3` branch is already updated: https://github.com/Yalantis/Koloda/commit/eea23944361a124b0502043718be50f13a53e9f2

**Comment by charlesmarino1** [comment]
@serejahh it doesn't compile.. why would you close ?
