### ISSUE TITLE
Failure to use Carthage

### ISSUE THREAD

**Issue by joshuaTTL** [Yalantis/Koloda#223]
# Report
### What did you do?

> I'm trying to use Carthage to add Koloda to my project. I used Coacopod before, which did not work and now Carthage gives me a thing like this.
### What did you expect to happen?

> I expect Carthage to work properly
### What happened instead?

> I got something like this 

**\* Cloning Koloda
**\* Cloning pop
**\* Checking out pop at "1.0.9"
**\* Checking out Koloda at "3.1.2"
**\* xcodebuild output can be found in /var/folders/xb/3ml7m20x7x53551fldj2v_1w0000gn/T/carthage-xcodebuild.gSzH9F.log
**\* Building scheme "pop-tvos-framework" in pop.xcworkspace
**\* Building scheme "pop-ios-framework" in pop.xcworkspace
**\* Building scheme "pop-osx-framework" in pop.xcworkspace
**\* Building scheme "Koloda" in Koloda.xcodeproj
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
warning: no umbrella header found for target 'Koloda', module map will not be generated
warning: no umbrella header found for target 'Koloda', module map will not be generated
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Justin/Documents/Irene_programming/Irene/Carthage/Checkouts/Koloda/Koloda.xcodeproj -scheme Koloda -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
### Your Environment
- [ ] Version of the component:
- [ ] Swift version: 3.0
- [ ] iOS version: 9.0
- [ ] Device: _insert here_
- [ ] Xcode version: 8.0
- [ ] If you use Cocoapods: no
- [ ] If you use Carthage: nothing turns out
### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by Neonkoala** [comment]
I encountered this issue too. The build log indicated the master repo isn't updated for Swift 3 syntax. You can work around this using the `swift-3` branch like so:

```
# Require version 3.1.x
github "Yalantis/Koloda" "swift-3"
```

**Comment by jaimeagudo** [comment]
@joshuaTTL here you have a working pod config for swift 3 https://github.com/jaimeagudo/koloda-swift-3-pod

**Comment by Vodolazkyi** [comment]
This bug fixed in https://github.com/Yalantis/Koloda/pull/251.
Will be updated in version 4.0
