### ISSUE TITLE
Make Swiping Easier

### ISSUE THREAD

**Issue by mogsten** [Yalantis/Koloda#227]
Hi, I am currently rebuilding an existing app and I am using your library, I would like to know if its possible to change the hardness of swiping a card, it seems way to tough at the moment, it needs to be easier, it took me 4 tries to swipe 1 card. The previous version of my app using a custom solution swiped instantly but had a few crashing issues.
Thanks in Advance

**Comment by vvit** [comment]
@mogsten, have you used this:
```
func kolodaSwipeThresholdRatioMargin(koloda: KolodaView) -> CGFloat? {
    return 0.5
}
```
from `KolodaViewDataSource`
