### ISSUE TITLE
Make ability to skip current visible card

### ISSUE THREAD

**Issue by patthehuman** [Yalantis/Koloda#228]
# Report

I would like a way to specifically skip the current visible card.
## A feature request

A feature to add a way to skip current visible card
### How should it look like?

Similar to the undo animation, except it will remove the current visible.

**Comment by patthehuman** [comment]
If anyone has any ways to simulate this, please let me know. I have been trying to iterate the cards, but I have only been able to hack together a jump or skip solution.

**Comment by freaqed** [comment]
Hey @patthehuman!
Please try to implement it with `koloda(_:didSwipeCardAt:in:)` delegate's method. 
Something like that:
```
func koloda(_ koloda: KolodaView, didSwipeCardAt index: Int, in direction: SwipeResultDirection) {
    if index == 2 {
      kolodaView.swipe(direction)
    }
}
```
I tested it in example project and it does the trick. Let me know if it doesn't helped.
