### ISSUE TITLE
this is a question, as a Newbie. 

### ISSUE THREAD

**Issue by jasan-s** [Yalantis/Koloda#23]
I wanted to try using this with data from parse.com, I'm familiar with pulling data in tableview controller using cellforrowatindexpath and updating tableview cell, is there something similar way to achieve that with Koloda. The example uses static images, but i want to populate a view from data from parse.com and update each card accoringly (label, uiimageview) .

**Comment by AEugene** [comment]
Hello. Thank you for the question. 
Data source method
```swift
 func kolodaViewForCardAtIndex(koloda: KolodaView, index: UInt) -> UIView
```
Takes any UIView. So just create the view you need(for example from xib) and return it in this method.

**Comment by jasan-s** [comment]
Just a follow up question AEugene, Can a UIView contain multiple objects in it (multiple UIImage, labels, button). And if it's loading from a UIView , will i use kolodaDidSwipedCardAtIndex to call to update the UIView every time with next photo for imageview and string for label.text?. Also wnat to say fantastic job on this repo.

**Comment by AEugene** [comment]
Sure. The view, that you return in data source method, is added as subview to card, just as content view for cell. Just setup proper layout and return the right view. If you have problems with it, we can prepare quick demo code.

**Comment by jasan-s** [comment]
Thanks for the prompt reply. I'll try to figure this out. If you do have the time, would really appreciate a demo(ANd many other Newbies like me) where you're pulling multiple objects from the web  and loading to a UIview and then loading to the cards( kolodaViewForCardAtIndex) , and reloading when pulled data runs out. Thanks.

**Comment by AEugene** [comment]
Take a look at "networking_example" branch. There is the example you're looking for.

**Comment by jasan-s** [comment]
Thank you very much for taking the time. One thing i did notice in  original example and the networking example is that the once the cards run out , the reloaddata() is called which refreshes the view which breaks the User experience, Comparing it to tinder the cards just keep loading as you swipe, I don't think they load all the users at once. Should i just create 2 Ui views and load one initially and load the other when the second to the last card index (n-1) if n is the total number of cards and pass to the viewforcardatindex function when when the cards run out. and keep toggling between the 2 UiView?

**Comment by jasan-s** [comment]
Your networking example helped a ton. Got it to work with parse.com, Thanks again. Now only if i can figure out to continuously load data without reloading view.

**Comment by AEugene** [comment]
The trick is easy you have delegate method
```swift
    func kolodaDidSwipedCardAtIndex(koloda: KolodaView, index: UInt, direction: SwipeResultDirection) {
```
inside this method add something like this
```swift
    if dataSource.count - index < 5 {
        fetchMoreCards()
    }
```

**Comment by jasan-s** [comment]
So I would update the numberofcards as well in the same function by running
data source function?

**Comment by jasan-s** [comment]
I was trying to reuse the index number of array for data but I guess it
makes sense to just keep appending to the array.

**Comment by AEugene** [comment]
You don't have to update numberofcards manually, just call kolodaView.reloadData after appending to your dataSource array.

**Comment by jasan-s** [comment]
Great , Got it :). One more thing the

    func kolodaDidSelectCardAtIndex(koloda: KolodaView, index: UInt) is ran
when anywhere on the Kolodaview is tapped, however I have my
KolodaPhotoView.xib like this Below:  With 2 image views and a button. I
wanted to launch a certain function when UIimage A is tapped and a separate
function when Uiimage B is tapped or when the button is flicked in certain
direction launch another function. I added UITapgesture recoginzer to each
UiImage view and added action in the  KolodaphotoView.swift with a function
of print statement   but that action is not recogined in the Custom Koloda
View when running the app .  Any thoughts.

[image: Inline image 1]

**Comment by DanielOrmeno** [comment]
Hello @jasan-s, did you come up with a solution for this? I've been trying to get a button action outlet working in my custom card view but the outlets are not getting fired. 

Cheers!

**Comment by pk75** [comment]
Can I use koloda in table row. If yes then how as I tried a way same as we do with collection in table row but it sends bad access when I set datasource.

**Comment by Miladinho** [comment]
@AEugene 

I am trying to pass in a UITableView instance in the viewForCardAt data source method. The tableview shows, but the custom cells I hookedup to this table does not show. Any insight would be much appreciated.

**Comment by MARS1** [comment]
When a Koloda card initially loads, it starts at scale 0 and expands to scale 1.0 bursting out from the center, is there a way to make the cards just load at about 95% scale and then grow the remaining 5%? It just take too long for the user to see that pop out from the center transition which I don't know the exact name for it. Any help would be great.

**Comment by mteera** [comment]
Hi, looking at the previous question, where can the "networking_example" branch be found?
