### ISSUE TITLE
Release Version for Swift 3

### ISSUE THREAD

**Issue by AndrewBarba** [Yalantis/Koloda#230]
Would love to get the Swift 3 version released as v4, any plans for that?

**Comment by AndrewBarba** [comment]
@serejahh Any updates on this?

**Comment by deada92** [comment]
it really should be as master atleast

**Comment by serejahh** [comment]
Now it's available in `4.0`

**Comment by ngominhtrint** [comment]
I've got error when `pod install` with `pod 'Koloda', '~> 4.0'`. Help me, please!

**Comment by serejahh** [comment]
@ngominhtrint what the error did you get?

**Comment by ngominhtrint** [comment]
```
[!] Unable to satisfy the following requirements:

- `Koloda (~> 4.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Koloda (~> 4.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

Above is error. But I try to put `pod 'Koloda', :git => "https://github.com/Yalantis/Koloda.git", :branch => "swift-3"` to my Podfile, instead of `pod 'Koloda', '~> 4.0'` And it solves 👍

**Comment by serejahh** [comment]
Did you run `pod repo update`? It fetches all needed podspecs

**Comment by ngominhtrint** [comment]
Great man, it works.. Thank you 👍

**Comment by serejahh** [comment]
You're welcome 👍
