### ISSUE TITLE
Flashing problem - Cards "flash" when app is loaded and Kolada stack is the default view.

### ISSUE THREAD

**Issue by sb2059** [Yalantis/Koloda#233]
Do you have any recommendations around preventing this?

**Comment by vvit** [comment]
Sometimes it happens on my side too when I quickly swipe cards. Maybe some kind of animation collision.

**Comment by felixdkatt** [comment]
I just return false in the should show animation method if its the first view. then turn it back on when all loading is done.

**Comment by freaqed** [comment]
closed via #259
