### ISSUE TITLE
Unknown class KolodaView in Interface Builder file.

### ISSUE THREAD

**Issue by moger777** [Yalantis/Koloda#235]
###  What did you do?

> I added a view in a storyboard and made it inherit fro KolodaView

### What did you expect to happen?

> I expected the controller to load properly

### What happened instead?

> I got the following error:

Unknown class KolodaView in Interface Builder file.

### Your Environment

- Version of the component: 2aea10e0ae955814e38fc815ff38c0b20fb126ea
- Swift version: 3.0.1
- iOS version: 10
- Device: iphone 5 simulator
- Xcode version: 8.1
- If you use Carthage: 0.18.1

### Project that demonstrates the bug

> The original project is proprietary but I was able to reproduce in dummy project: https://github.com/moger777/ExampleOfCrash

**Comment by satoshin21** [comment]
@moger777 
I encountered this error too.
At that time, I specified `Module name` of `KolodaView` in interface builder like below and worked successfully.
<img width="185" alt="2016-12-15 11 45 53" src="https://cloud.githubusercontent.com/assets/4471149/21210224/9ce92f56-c2bc-11e6-9c90-1962d379ee28.png">
