### ISSUE TITLE
Crash, when user made fast swipe few times.

### ISSUE THREAD

**Issue by robertherdzik** [Yalantis/Koloda#24]
As in subject did you guys know something about this issue?

**Comment by AEugene** [comment]
We didn't know about this issue. Could you give us console log?

**Comment by robertherdzik** [comment]
It's crashing in KolodaView.swift line:
<img width="880" alt="screen shot 2015-08-20 at 15 41 38" src="https://cloud.githubusercontent.com/assets/10906921/9384619/044d68a2-4752-11e5-9e8d-ed123e91fb44.png">

There is no any log in console.

**Comment by castus** [comment]
+1

**Comment by AEugene** [comment]
Does issue appear with manual swiping or with koloda methods?

**Comment by robertherdzik** [comment]
Only with manual swiping.

**Comment by AEugene** [comment]
I can't reproduce it. Did you get this crash on simulator? Do you have some reproduce steps?

**Comment by robertherdzik** [comment]
It is very easy to reproduce on physical device. Steps to reproduce are simple, you have to swipe e.g. to right site relatively fast(after couple times app should crash). During this library "stress test" some UI glitches are also visible.

**Comment by jasan-s** [comment]
I tested this just recently as well on a device. it crashes in either direction if swiped at high speed

**Comment by rajesh-situ** [comment]
facing the same issue in the latest version.
<img width="1115" alt="screen shot 2018-10-08 at 1 41 02 pm" src="https://user-images.githubusercontent.com/10433518/46597945-d98a7080-caff-11e8-8dad-8aced857bffa.png">

could you please help fixing this?
