### ISSUE TITLE
Swift 3 pod-spec problem

### ISSUE THREAD

**Issue by kaka21garuda** [Yalantis/Koloda#242]
# Report

> There has been countless errors in the Koloda Framework

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What did you do?

> I run `pod install` with `pod 'Koloda'` inside my pod file 

### What happened instead?

> Type errors, optional errors, code is not compiling 

### Your Environment

- Version of the component: 3.1.2
- Swift version: 3.0
- iOS version: 10
- Device: iPhone 7
- Xcode version: 8.0

### Project that demonstrates the bug

> https://github.com/kaka21garuda/Alpha/tree/koloda

**Comment by serejahh** [comment]
Hi @kaka21garuda! It happens because `3.1.2` doesn't support swift 3. Please have a look at #230

**Comment by snehasen1990** [comment]
3.1.2 doesn't support swift 3? then how to run project on xcode8?

**Comment by serejahh** [comment]
pull `swift-3` branch instead
