### ISSUE TITLE
tableView scrolling cancels drag gesture

### ISSUE THREAD

**Issue by xiaosongshu** [Yalantis/Koloda#244]
I'm using a tableView inside my kolodaView to show multiple pictures vertically, and am having some issues with gesture recognition. Is there something I should be doing to make dragging smoother?

Issues
1. on screen load, dragging down the tableview vertically doesn't move the card. This is expected given my gesture is triggered on the tableView and instead causes vertical scrolling of the tableView (vertical bounce). Is there an easy way to make this initial drag down gesture activate dragging the kolodaView instead of dragging the tableView?

2. when scrolling the tableView mid-way and then immediately trying to drag the kolodaView, the horizontal drag gesture is not recognized. It seems the tableView is cancelling the drag gesture on the kolodaView as the tableView is scrolling vertically. Is there anything I can do to make the kolodaView "more responsive" so that even during mid-way scroll, the card responds to the drag gestures as well?

My dataSource is setup as such (with the tableView inside the profileDataViewController):

```
 func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView {
        
        let controller = R.storyboard.profile.profileDataViewController()!
        let profile = userProfiles[index]
        controller.profile = profile
        
        self.addChildViewController(controller)
        
        controller.view.frame = koloda.bounds
        
        let view = UIView(frame: koloda.bounds)
        view.clipsToBounds = true
        
        view.addSubview(controller.view)
        return view
    }
```

**Comment by simonpac** [comment]
Did you figure this out?

**Comment by xiaosongshu** [comment]
I did not unfortunately. Any ideas?

**Comment by freaqed** [comment]
Hi guys.
Koloda isn't developed for nesting collections. It's a bad approach to have any nested collections since it mocks interaction flow. And I don't think you could find a good solution for this (well, except some workarounds).
Closing the issue as not related to Koloda.
