### ISSUE TITLE
Double tapping a card

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [Yalantis/Koloda#247]
## A feature request

I'd like a way for users to be able to double tap a card.  In my use case this is so they can either tap once to expand the card to a full screen scrollable view or double tap to zoom on the image.

###  What do you want to add?

I propose adding another method to the `KoladaViewDelegate`:

`func kolada(_ kolada: KoladaView, didDoubleTapCardAtIndex index Int)`

Implementation wise it looks fairly straight forward.  The `setup()` method in `DraggableCardView` on line 87 would have two gesture recognizers using `numberOfTapsRequired`.

**Comment by serejahh** [comment]
Hi @ChrisLowe-Takor. You can add a gesture to your custom card and add any action you want
