### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Al-Nibras** [Yalantis/Koloda#25]
when compiler execute this function which is called in viewDidLoad() before Koloda dataSource and delegate have their values
it crashes and shows me the message above

the function loads the new users from Parse
the decleration of the function is : 

 func loadNewUser()
    {
        
        let query = PFQuery(className: "_User")
        
        switch (query)
        {
        case query.whereKey("verifiedToLogin", notEqualTo: true):
            fallthrough
        case query.whereKey("verifiedToLogin", notEqualTo: false):
            fallthrough
        default:
            arr = NSArray(array: query.findObjects()!)
           numberOfCards = UInt(arr.count)
            break
        }
        print("Array has \(arr.count) elements")
        kolodaView.reloadData()
    }

I tried to set "numberOfCards = UInt(arr.count)" as a comment but it still crashes
& shows me that message

**Comment by Al-Nibras** [comment]
This is the command that it selects it for me as the issue:
countOfCards = Int(dataSource!.kolodaNumberOfCards(self))
declared in reloadData() & setupDeck() functions at KolodaView class

**Comment by tomekh7** [comment]
You have to set dataSource before calling raloadData().

**Comment by AEugene** [comment]
Yep. As you can see, dataSource property isn't optional, so Koloda needs it for proper work.

**Comment by Al-Nibras** [comment]
Oh, thanks a lot, it works fine now
