### ISSUE TITLE
Forward touch events to view beneath Koloda View

### ISSUE THREAD

**Issue by xeoneux** [Yalantis/Koloda#252]
![screen shot 2016-12-29 at 10 34 29 am](https://cloud.githubusercontent.com/assets/3099626/21537134/b59da634-cdb2-11e6-8110-3701a32bb320.png)

The login button does not receive the touch events.

I've tried creating a custom class and overriding the behaviour but it crashes the application.

```swift
class CustomKolodaView: KolodaView {

    var isAtLastCard = false

    override func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
        if isAtLastCard {
            return true
        }

        return super.point(inside: point, with: event)
    }

}
```

What's the best way to pass all the touch events to the view behind Koloda View?

**Comment by xeoneux** [comment]
@serejahh Any suggestions please?

**Comment by serejahh** [comment]
@AEugene

**Comment by xeoneux** [comment]
@AEugene Any solutions please?

**Comment by AEugene** [comment]
hi @xeoneux . Could you give an example project?
