### ISSUE TITLE
Is there a way to call `viewForCardAt` again?

### ISSUE THREAD

**Issue by xiaosongshu** [Yalantis/Koloda#253]
```
    func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView {       
        let controller = R.storyboard.profile.profileDataViewController()!
        let profile = userProfiles[index]
        controller.profile = profile
        
        self.addChildViewController(controller)
        
        controller.view.frame = koloda.bounds
        
        let view = UIView(frame: koloda.bounds)
        view.addSubview(controller.view)
        return view
    }
}
```

Each object in `userProfiles` contains photos that I pull asynchronously. The issue I'm having is the photos are downloaded, `userProfiles` is updated in the Koloda View Controller, but the updated `userProfiles` are not being passed to my profileDataViewcontroller (ie. `viewForCardAt` is not being called again). Is there anyway I can call this function again?

**Comment by freaqed** [comment]
Hi @xiaosongshu!
Have you tried force kolodaView to update it's layout? E.g. by calling `kolodaView.setNeedsDisplay()`. If so, please provide us some example project to reproduce your bug. Thanks!
