### ISSUE TITLE
How to properly leave the kolodaview

### ISSUE THREAD

**Issue by tirrorex** [Yalantis/Koloda#255]
Hello, here are the versions of the tools i use : 

koloda 3.1.2
swift 2.2
xcode 7.3.1

I check my condition in didSwipeCardAtIndex, and decide then if i have to trigger my segue or not.
The problem here is that before the segue, the next card is displayed for a second.

What is the proper way here to do this since shouldSwipeCardAtIndex will not detect a programmatical swipe anyway?

**Comment by freaqed** [comment]
Hello @tirrorex!
According to it's name, `kolodaView(_:didSwipeCardAt:in:)` called when card already swiped.
If you want to trigger segue instead of swiping card the simplest way to do that would be implementing `koloda(_:shouldSwipeCardAt:in:)` and check `direction`. For desired one just trigger segue and return `false` so koloda won't swipe.

**Comment by tirrorex** [comment]
@freaqed according to the documentation and actual behaviour, `kolodaView(_:didSwipeCardAt:in:)` is not called if the swipe is trigger programmatically.
Unless you can provide me with a workaround for this please reopen the issue

**Comment by freaqed** [comment]
Ok, got you. Will work it out

**Comment by freaqed** [comment]
So I just checked that. In the latest version of a component '4.1' it seems to be working fine.
When I call `swipe(_:force:)` delegate's method called properly: `koloda(_:shouldSwipeCardAt:in:)` and then `kolodaView(_:didSwipeCardAt:in:)`. The same is true for manual swiping.
I've also check the cancellation, and it works fine. If I release finger before animation finished only `koloda(_:shouldSwipeCardAt:in:)` method called.

**Comment by tirrorex** [comment]
I meant `koloda(_:shouldSwipeCardAt:in:)`  (will update my previous comment to not confuse eventual users)
If this method is called when the swipe is cancelled it is gonna be tricky to figure things out, because the segue would already be fired.
Sorry for the misunderstanding.

Is 4.1 compatible with swift 2.3?
Since we are a few days from launch we couldn't update all the pods, stabilizing the app and shipping it was more urgent than moving to swift 3.1

**Comment by freaqed** [comment]
Oh, now I got it. So `koloda(_:shouldSwipeCardAt:in:)` also called with `swipe(_:force:)`, I guess it's been fixed in one of the releases.
No, I don't think `v4.1` is compatible with swift 2.3. Can't check it

**Comment by tirrorex** [comment]
Will get back to it after launch, last few days have been crazy.
Any chance you guys know the last version compatible with swift 2.3?
Might have to fork the repo for a while :/

**Comment by sunil-biloniya** [comment]
Up side swipe direction is not work until I swipe it forcefully but It dose not work
