### ISSUE TITLE
How to detect action in KolodaView

### ISSUE THREAD

**Issue by longhoang2984** [Yalantis/Koloda#258]
Hi,

I'm create tinder app with this lib, I have a bookmark button, and I added target with another function but when I click in the button, the func didSelect always run first, how can I run selector func first

swipeView?.bookMarkCupid.addTarget(self, action: #selector(saveCupid), for: .touchUpInside)

**Comment by freaqed** [comment]
Hey @longhoang2984!
Could you explain (or even show screenshots) of what you're doing?
Code snippets would also be grate, because it's not clear what you're doing.

**Comment by niennonno** [comment]
Hey I am facing the same problem. 

I am passing a a custom `UIView` created programmatically and reloading the` kolodaView`. The buttons are not calling their targets. Can you please shed some light on this.

**Comment by mukeshrajput** [comment]
func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView {
        let vc  = self.storyboard?.instantiateViewController(withIdentifier: "test") as! test
         addChildViewController(vc)
        print(index)
        print(vc.name.text) 
        
        vc.name.text = (self.total_posts.object(at: index) as! NSDictionary).value(forKey: "user_name") as! String
   
        vc.view.translatesAutoresizingMaskIntoConstraints = false
        return vc.view
    }

//ERROR "Fatal error: Unexpectedly found nil while unwrapping an Optional value kolodaview"
when I am printing vc.name,text

**Comment by freaqed** [comment]
@niennonno, @muhasturk guys I don't think your issues are related. If you still facing them, please start a new issue.

@longhoang2984, if you still got that problem please share some code and reopen it.
