### ISSUE TITLE
changing colors, buttons

### ISSUE THREAD

**Issue by mjpablo23** [Yalantis/Koloda#260]
How do I change the background image in the koloda view?  I'd like to change it to something other than red.

![image](https://cloud.githubusercontent.com/assets/12970136/22848157/3cf57e5c-efa7-11e6-85a4-c13041b40c4f.png)

# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What do you want to add?

> Please describe what you want to add to the component. 

### How should it look like?

> Please add images. 

###  What did you do?

> Please replace this with what you did. 

### What did you expect to happen?

> Please replace this with what you expected to happen.  

### What happened instead?

> Please replace this with what happened instead.

### Your Environment

- Version of the component: _insert here_
- Swift version: _insert here_
- iOS version: _insert here_
- Device: _insert here_
- Xcode version: _insert here_
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by mjpablo23** [comment]
I figured out how to change the buttons and title.  but how do I change the background color?

**Comment by freaqed** [comment]
Hey @mjpablo23!
As far as I can see from the example project, it's enough to change the `backgroundColor` for a root view of your controller:

![image](https://cloud.githubusercontent.com/assets/5273603/25952888/8ffc1bf6-366a-11e7-9748-08b91510b728.png)
