### ISSUE TITLE
How to add  LIKE and NOPE image on left and right  cornor on card

### ISSUE THREAD

**Issue by sahabe1** [Yalantis/Koloda#261]
Hi Yalantis,
Can we add LIKE and NOPE image on left and right  cornor on card. please see the following image.

![screenshot_20170215-122935](https://cloud.githubusercontent.com/assets/1065015/22963941/f5ca137a-f37b-11e6-9878-519cd751f181.png)

![screenshot_20170215-122942](https://cloud.githubusercontent.com/assets/1065015/22963942/f5cdfff8-f37b-11e6-803c-ad0ab9fe478c.png)

**Comment by barcister** [comment]
add 2 imageViews to your view, that set their alpha values to 0 and upon movement depending on the swipe direction start to change their alpha values to 1.

**Comment by tomekh7** [comment]
You can use custom implementation of `OverlayView` for such feature.

**Comment by freaqed** [comment]
Hi @sahabe1! Have you solved this? Solutions above should do that. Please let us know if you tried one of them.
