### ISSUE TITLE
Change swipe animation duration

### ISSUE THREAD

**Issue by sahabe1** [Yalantis/Koloda#262]
Can I modidied left and right swipe animation duration

**Comment by sjoness** [comment]
@sahabe1 I opened a [PR](https://github.com/Yalantis/Koloda/pull/256) for this, but in the mean time, you can use my fork

**Comment by sjoness** [comment]
@sahabe1 my [pull request](https://github.com/Yalantis/Koloda/pull/256) has now been merged into master. It's probably worth closing this issue now.

**Comment by freaqed** [comment]
@sahabe1, @sjoness thanks for contribution! 
As it's been mentioned, PR from sjones already merged and will be added in a new release.
