### ISSUE TITLE
How to add action to button added on Koloda view

### ISSUE THREAD

**Issue by sahabe1** [Yalantis/Koloda#267]
Hi,

I am facing proble to add action on button . I have added user icon and button but when i click button its calling didselect as well as button method . so can i avoid calling did select when i click button .please see attachment
![simulator screen shot mar 3 2017 4 28 39 pm](https://cloud.githubusercontent.com/assets/1065015/23562571/fdd1ca6e-0068-11e7-8058-3a0dd258be0f.png)

please help

Thanks

**Comment by guumeyer** [comment]
Hello, @sahabe1,
You could create your custom view class with yours controls inside and add the button action inside.
