### ISSUE TITLE
Major bug in the buttons that substitute the left and right gestures

### ISSUE THREAD

**Issue by midhetfatema94** [Yalantis/Koloda#268]
# Report

###  What did you do?

I have a basic requirement of swiping a view left and right which also has two buttons at the bottom, much like what was done in the sample gifs. When the view appears on the screen and before swiping left or right, if i directly click the accept or reject button, it gives me this error on loop 
`This NSLayoutConstraint is being configured with a constant that exceeds internal limits.  A smaller value will be substituted, but this problem should be fixed. Break on BOOL _NSLayoutConstraintNumberExceedsLimit() to debug.  This will be logged only once.  This may break in the future.`
and crashes with a bad instruction flag.

### Your Environment

- Version of the component: 4.0
- Swift version: 3.0
- iOS version: 10.0
- Device: iphone6s
- Xcode version: 8.0
- If you use Cocoapods: 

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C68)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2732bba7c4679e749c18b9b0658e537ccd7656ab
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

**Comment by Vodolazkyi** [comment]
Hi, can you provide us with sample project ?

**Comment by midhetfatema94** [comment]
Okay, will do it in a couple of days if that's okay.
And also, can I contribute to your project in any way? I really liked the
plugin.

**Comment by Vodolazkyi** [comment]
Yes, of course !

**Comment by midhetfatema94** [comment]
Hi, 
So I did make a sample project, and I think that it was probably my mistake because I didn't understand the documentation first time around. Now, everything is working fine. Anyway, if you want to check it out, here's the link to the sample project: https://github.com/midhetfatema94/KolodaSample

I think I am going to close this issue.
