### ISSUE TITLE
Isssue when remove index

### ISSUE THREAD

**Issue by BilalReffas** [Yalantis/Koloda#269]
When the user swipe I remove my array on the `index` which the datasource returns
I'm trying to remove my array on 
```swift
func koloda(_ koloda: KolodaView, didSwipeCardAt index: Int, in direction: SwipeResultDirection) {
  self.array.remove(at: index)
}
```

The problem is afert that I will get an `fatal error: Index out of range`

on
```swift
  func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView {}
```
What I'm doing wrong ? :/

**Comment by mrformidable** [comment]
I am also having the same problem did you find a solution?

**Comment by BilalReffas** [comment]
Someone can help us here please ?

**Comment by BilalReffas** [comment]
@freaqed are you working on this ?

**Comment by freaqed** [comment]
@BilalReffas, we're going to fix major bugs and update version of a Koloda in a nearest future. Thanks for reporting!

**Comment by BilalReffas** [comment]
Great to hear thank you! 🙏. What does "nearest future" mean? :/

**Comment by Vodolazkyi** [comment]
Hi, just because it's unexpected behavior, you shouldn't remove card right after you showed it. You have `func kolodaNumberOfCards(_ koloda: KolodaView) ` where you says number of card that should be in kolada and `func koloda(_ koloda: KolodaView, viewForCardAt index: Int)` keep old index after you remove element from array. Does it make sense for you ?

**Comment by BilalReffas** [comment]
Ahh not really. I aspect that it work's similar like a `UITableView` from apple. 🤔 But I'm not really sure about this behavior.. Is there a small documentation about it? :)

**Comment by Vodolazkyi** [comment]
If you remove element from your datasource  in `TableView` without calling `reloadData()` its also lead to `error: Index out of range`

**Comment by BilalReffas** [comment]
Yes for sure. But I'm calling `reloadData`.. ☹️

**Comment by Vodolazkyi** [comment]
Koloda keep your old index. You should reset index by calling `kolodaView?.resetCurrentCardIndex()` before calling `reloadData()`

**Comment by BilalReffas** [comment]
thank you I will check this. I think this could fix the issue.

**Comment by BilalReffas** [comment]
Interesting 

this work 👍

```
            self.kolodaView.resetCurrentCardIndex()
            self.dataSource.remove(at: index)
            self.kolodaView.reloadData()
```

this do not work for me 👎

```
            self.dataSource.remove(at: index)
            self.kolodaView.resetCurrentCardIndex()
            self.kolodaView.reloadData()
```

**Comment by Vodolazkyi** [comment]
This solved your problem ?

**Comment by BilalReffas** [comment]
Yes it solved my problem. But I do not really understand that
