### ISSUE TITLE
change background cards alpha value

### ISSUE THREAD

**Issue by Al-Nibras** [Yalantis/Koloda#27]
I want to decrease the transparent(increase alpha value to 0.8) of cards which are in the backgrounds behind the first card?
their alpha values become less when I swipe to anywhere or clicked on any button
I want to make them like the first card (explained in the first photo below)!

So, how to...please???

![simulator screen shot dhu l-q 7 1436 ah 12 17 35 am](https://cloud.githubusercontent.com/assets/13896573/9419420/21233246-4864-11e5-9b64-e3c878daebf3.png)
![simulator screen shot dhu l-q 7 1436 ah 12 17 40 am](https://cloud.githubusercontent.com/assets/13896573/9419421/215eb870-4864-11e5-9153-c890b7fd29a5.png)

**Comment by AEugene** [comment]
You can simply set alphaValueSemiTransparent property
Example:
```swift
kolodaView.alphaValueSemiTransparent = 0.8
```
Note: You should set it before koloda draw cards.
