### ISSUE TITLE
How to determine swipe left and rght

### ISSUE THREAD

**Issue by sahabe1** [Yalantis/Koloda#270]
HI ,

I Want to call API when user Swipe left and Right. In which method I can determine swipe direction

**Comment by mrformidable** [comment]
Implement this
    func koloda(_ koloda: KolodaView, didSwipeCardAt index: Int, in direction: SwipeResultDirection) {
       
        if direction == SwipeResultDirection.right {
             // implement your functions or whatever here
            print("user swiped right")
        } else if direction == .left {
        // implement your functions or whatever here
            print("user swiped right")
        }
     
    }

**Comment by sahabe1** [comment]
i am using  same method my requirement is i need to call 3 diffrent API for Left Swipe, Right Swipe and button click (right swipe) when i click button above method also called (for riht direction). but i do not want to call  please see attachment 'didSwipeCardAt index: Int, in direction: SwipeResultDirection' on button click . How can i do this
![simulator screen shot mar 10 2017 11 44 13 am](https://cloud.githubusercontent.com/assets/1065015/23808445/e766c022-05ef-11e7-8a29-40af34760c4e.png)

**Comment by freaqed** [comment]
Hi @sahabe1!
`KolodaView`s delegate is not designed for that purpose. When you call `swipe(_:force:)` it will call `koloda(_:didSwipeCardAt:in:)` according to api of it's delegate. So for your particular situation the simplest solution would be store the source of a swipe (button/manual) and then inside delegate's method check that state.
