### ISSUE TITLE
DraggableCardView Deallocating Crash

### ISSUE THREAD

**Issue by Sadoge** [Yalantis/Koloda#274]
**report a bug**.

When swiping for multiple times the application crashes. Adding image that shows the debug.
![screen shot 2017-03-24 at 5 45 37 pm](https://cloud.githubusercontent.com/assets/11598837/24289013/70b39b14-10ba-11e7-9630-d961ba500b90.png)

### Your Environment

- Version of the component: 4
- Swift version: 3
- iOS version: 10.2
- Xcode version: 8.2.1

**Comment by Vodolazkyi** [comment]
Can you provide example project with this bug or detailed steps to reproduce ?
