### ISSUE TITLE
Wrong frame

### ISSUE THREAD

**Issue by BilalReffas** [Yalantis/Koloda#278]
Sometimes after loading the data from the server the `KolodaView`showing the wrong frame. 

<img width="395" alt="bildschirmfoto 2017-04-19 um 13 35 53" src="https://cloud.githubusercontent.com/assets/8920003/25178548/801fba3c-2506-11e7-9c74-54674a16518b.png">

**Comment by Vodolazkyi** [comment]
Can you provide us with sample project please ?

**Comment by BilalReffas** [comment]
Mhh sorry I can not share the code :( but please check this #147

**Comment by Bathibabu** [comment]
Hi anyone resolved this issue,can you please share the code.

**Comment by alexsanderkhitev** [comment]
@BilalReffas I faced the same issue.

**Comment by tenaz3** [comment]
Same issue

**Comment by freaqed** [comment]
Closed via #259. Let us know if the issue still exist
