### ISSUE TITLE
How to make card more senstive

### ISSUE THREAD

**Issue by sahabe1** [Yalantis/Koloda#279]
card are not smoothely swiping left or right. some time when swipe happen it should remove card

**Comment by freaqed** [comment]
Hi @sahabe1!
Could you please fill the template for an issue? Because it's not clear what you're asking for.

**Comment by GonzalezAnguita** [comment]
I think i have the same question. When performing a swipe over a card, the bounds in which the card is removed from the top of the stack force the user to perform the swipe to almost the end of the screen. Is there any way of changing those bounds so the card removal is more sensitive?

**Comment by robbiet480** [comment]
Also having the same issue. Any suggestions?

**Comment by AtharvaVaidya** [comment]
+1

**Comment by localsDeveloper** [comment]
set the delegate 'kolodaSwipeThresholdRatioMargin' with a value between 0 and 1.

**Comment by freaqed** [comment]
As @localsDeveloper said Koloda's API have `kolodaSwipeThresholdRatioMargin(_:)` method for that purpose.
