### ISSUE TITLE
calling "resetCurrentCardIndex" doesn't reload the koloda cards

### ISSUE THREAD

**Issue by software-developer-eng** [Yalantis/Koloda#283]
###  What did you do?
Use "resetCurrentCardIndex" to reset the current card index
func kolodaDidRunOutOfCards(_ koloda: KolodaView) {
  kolodaView.resetCurrentCardIndex()
}

this like the source code in the library example, it is not working in the example also

Also tried this
func kolodaDidRunOutOfCards(_ koloda: KolodaView) {
  kolodaView.resetCurrentCardIndex()
  kolodaView.reloadData()
}

### What did you expect to happen?
Reset the card index to 0
and then reload the cards again

### What happened instead?

it cause to hide the visible cards and koloda view doesn't load cards
### Your Environment

- Version of the component: _insert here_
- Swift version: 3.0
- iOS version:10
- Device: simulator
- Xcode version: 8.2
- If you use Cocoapods:
### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 333e79b3fc7f1e5d3eb642e198260c971557a438
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

**Comment by Okizeme** [comment]
I have the same code as you but I think that it's actually the "kolodaDidRunOutOfCards" that is never called. I tried to call "resetCurrentCardIndex" elsewhere and it works, but the animation and layout are very buggy.

**Comment by freaqed** [comment]
Hi @software-developer-eng! 
Just checked example project and it seems to be working as expected. 
I just tap `like` button five times and `BackgroundAnimationViewController.kolodaDidRunOutOfCards(_:)` being called, which causes koloda to reload. Afterwards deck is reloaded and cards appears from start. 

Which version of koloda are you using?

Also, I noticed you're calling `kolodaView.reloadData()` after `kolodaView.resetCurrentCardIndex()` which doesn't make sense because `resetCurrentCardIndex` method calls `reloadData` inside.

**Comment by Okizeme** [comment]
You are right it's working properly for me aswell.
I had typo on the kolodaDidRunOutOfCards method name so the method was never called. Since I fixed it resetCurrentCardIndex is working fine.

**Comment by software-developer-eng** [comment]
Hi @freaqed 
Koloda version: 4.0
At "BackgroundAnimationViewController" the method "kolodaDidRunOutOfCards" is called but no card  appear and the screen become empty like the attaced image
![screen shot 2017-05-25 at 2 51 21 am](https://cloud.githubusercontent.com/assets/10545933/26430338/c07f4136-40ec-11e7-8072-f40e5a44e517.png)

**Comment by freaqed** [comment]
The problem in methods naming. Please check it once again if you're implemented the right one.

**Comment by mding5692** [comment]
I think this happens when the index is 0, I believe I'm getting this issue too where all the cards disappear, however I also called resetCurrentCardIndex() in my own function and not as part of a delegate function
