### ISSUE TITLE
Memory leak issue removing childviewcontroller

### ISSUE THREAD

**Issue by Teglgaard** [Yalantis/Koloda#285]
# Issue
I love this great library but I am unable to stop a memory leak. It happens even though I follow the guidelines for adding and removing subview from containers. The guide used: https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html.

In the function 
> func koloda(_ koloda: KolodaView, viewForCardAt cardIndex: Int) -> UIView 

I create a subViewController called swipeCardOverlay from storyboard then I add it as a child view controller with

> addChildViewController(swipeCardOverlay)

Then i set the frame for the swipeCardOverlay and add the subView to koloda with

>        koloda.addSubview(swipeCardOverlay.view)

Then i call didmove to parent viewcontroller with

>        swipeCardOverlay.didMove(toParentViewController: self)

The issue then happens when i try to remove it again so release the memory. I try to do this in the function

>    func koloda(_ thisKolodaView: KolodaView, didSwipeCardAt index: Int, in direction: SwipeResultDirection) 

where i get the current cards view by calling 

>            let currentCardView = koloda(thisKolodaView, viewForCardAt: Int(index))

I then get parent controller with 

>            let currentCardViewCntroller = currentCardView.parentViewController as! swipeCardOverlay

and remove it by calling these 3 methods

>currentCardViewCntroller.willMove(toParentViewController: nil)
        currentCardViewCntroller.view.removeFromSuperview()
        currentCardViewCntroller.removeFromParentViewController()

But for some reason this does not remove it from memory. Can someone point me in a direction to solve this problem so the app wont crash by swiping a lot of times.

**Comment by PravdaEvgen** [comment]
Hello, @Teglgaard . Thank you for using our framework. 
Here are some recommendations for you: 

- You don't need to set the frame when you are adding view for card in`func koloda(_ koloda: KolodaView, viewForCardAt cardIndex: Int) -> UIView`

**Comment by Teglgaard** [comment]
Hi @PravdaEvgen 
I thought I could fix it with your suggestion. I really believe that I understand your comments and how to implement it, but the issue persists. Is it possible that you can share your test project with me so I can compare and learn if I am doing just the slightest wrong. I know some time has gone by but I really hope that you can help anyway. We are starting the project up again now so any help will be appreciated!

I am testing on a project that I have slimmed down for finding the errors and from what I can see the problem comes from adding the addChildViewController

**Comment by Teglgaard** [comment]
I have now realized that the childviewcontrollers gets stuck whenever you reset the view. That means that additional 3 childviewcontrollers have to be removed when the koloda is reset. That solved the problem. I would love and think others will too, if you could include this in your example.
