### ISSUE TITLE
What is the best way to implement pagination?

### ISSUE THREAD

**Issue by alexsanderkhitev** [Yalantis/Koloda#287]
Hello! Thanks for the wonderful framework! Tell me how best to implement pagination (like a news feed).

**Comment by freaqed** [comment]
Hello, @alexsanderkhitev! There is no drop-in implementation for pagination in that lib. You can implement it on your own just like in regular table view (or collection view). Try to google for existing [solutions](https://www.google.com.ua/search?q=uitableview+pagination+swift&oq=uitableview&aqs=chrome.0.69i59j69i57j69i61j69i59j69i61j35i39.2032j0j7&sourceid=chrome&ie=UTF-8)
