### ISSUE TITLE
Wrong documentation description for using swift 3

### ISSUE THREAD

**Issue by Judgeman** [Yalantis/Koloda#292]
## Wrong documentation description for using swift 3

I am using Koloda Version 4.1 with swift 3.1.

The documentation says to implement the delegate and datasource function like this:
`func kolodaDidRunOutOfCards(koloda: KolodaView)`

But this implementation not matches and the functions not called.

Your call have no label for the first attribute "KolodaView" so the delegate and the datasource have to mute the first attribute like this:
`func kolodaDidRunOutOfCards(_ koloda: KolodaView)`

Please change the description in the documentation.

**Comment by freaqed** [comment]
Hello, @Judgeman. Thanks for pointing it out. Will update readme asap.

**Comment by Tykhonkov** [comment]
resolved
