### ISSUE TITLE
How to add label below the koloda view for image description?

### ISSUE THREAD

**Issue by kushalfm** [Yalantis/Koloda#296]
Hi Yalantis,
You have add image in kolada view for tinder like effect its look great, but I also want to add text below the image so that we can add description of image .

**Comment by AliAyasrah** [comment]
actually it is return view not image 
so you can create your customView and add what you like to 
image , label .... 

for example in this protocol 
 func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView
    {
        let customView = UIView()
        customView.frame = CGRect.init(x: 0, y: 0, width: 100, height: 200)
        customView.backgroundColor = UIColor.white     //give color to the view
        customView.center = self.view.center
        
        return customView //UIImageView(image: dataSource[Int(index)]);
        
    }

**Comment by eironeia** [comment]
I am facing the same problem and I have no idea how to solve it.

`func koloda(koloda: KolodaView, viewForCardAtIndex index: UInt) -> UIView {
        
        userImage = UIImageView()
        
        userImage.kf_setImageWithURL(url, placeholderImage: nil, optionsInfo: nil, progressBlock: nil) { (image, error, cacheType, imageURL) in
        
        }
        
        userImage.layer.cornerRadius = 12
        userImage.layer.masksToBounds = true

        let cardTextView = UIView()
        cardTextView.layer.cornerRadius = 8
        cardTextView.translatesAutoresizingMaskIntoConstraints = false

        userImage.addSubview(cardTextView)

        
        
        let cardTextViewLeading = NSLayoutConstraint(item: cardTextView, attribute: NSLayoutAttribute.Leading, relatedBy: NSLayoutRelation.Equal, toItem: userImage, attribute: NSLayoutAttribute.Leading, multiplier: 1, constant: 0)
        
        let cardTextViewTrailing = NSLayoutConstraint(item: cardTextView, attribute: NSLayoutAttribute.Trailing, relatedBy: NSLayoutRelation.Equal, toItem: userImage, attribute: NSLayoutAttribute.Trailing, multiplier: 1, constant: 0)
        
        let cardTextViewBottom = NSLayoutConstraint(item: cardTextView, attribute: NSLayoutAttribute.Top, relatedBy: NSLayoutRelation.Equal, toItem: userImage, attribute: NSLayoutAttribute.Bottom, multiplier: 1, constant: 0)
        
        let heightConstraint = NSLayoutConstraint(item: cardTextView, attribute: NSLayoutAttribute.Height, relatedBy: NSLayoutRelation.Equal, toItem: nil, attribute: NSLayoutAttribute.NotAnAttribute, multiplier: 1, constant: 100)
        
        NSLayoutConstraint.activateConstraints([cardTextViewLeading, cardTextViewTrailing, cardTextViewBottom, heightConstraint])
        
        return userImage
    }
`

**Comment by eironeia** [comment]
Solved checking this solution:

[https://github.com/Yalantis/Koloda/issues/23](url)
