### ISSUE TITLE
Hi I am new to Github and have no idea how to get started, can anyone help?

### ISSUE THREAD

**Issue by NuclearDuck** [Yalantis/Koloda#298]
# Report
Hi so I have no idea how to get Koloda up and running. I am new to github and honestly can't understand the readme to get it running. I have installed Koloda with Cocoa pods but that's about it, if anyone can give me some extra help on how to get started it would be greatly appreciated! thanks!

**Comment by RuttenYO** [comment]
Hi!
You'd better ask this question at https://stackoverflow.com or google how to use CocoaPods in your project.
