### ISSUE TITLE
`pod try` won't compile on Xcode 7.0b2

### ISSUE THREAD

**Issue by aaronbrethorst** [Yalantis/Koloda#3]

**Comment by AEugene** [comment]
Thanks for noticing, there is misspelling in readme. Try pod "Koloda"

**Comment by aaronbrethorst** [comment]
I did. The problem is likely an issue with the iOS 9.0 SDK or the changes in the latest version of Swift.

**Comment by AEugene** [comment]
Maybe, There is Swift 2 though. We didn’t test lib on beta versions. Can I help you somehow?

**Comment by aaronbrethorst** [comment]
I don't have access to older versions of Xcode.

**Comment by AEugene** [comment]
Here is Podfile example for swift 2.0
```ruby
use_frameworks!
pod "Koloda", :git => 'https://github.com/Yalantis/Koloda.git', :branch => 'swift2.0'
```
