### ISSUE TITLE
multiple target support for koloda view

### ISSUE THREAD

**Issue by mjpablo23** [Yalantis/Koloda#300]
# Report

I tried making a XCode project with multiple targets using the KolodaView pod.  It still works with the first target, but the second target is crashing here when I try to open the KolodaView: 

return Bundle.main.loadNibNamed("CustomOverlayView", owner: self, options: nil)?[0] as? OverlayView

The error is this:  

 *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIView 0x7fd523d158f0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key overlayImageView.'

Any suggestions?  Thanks.

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What do you want to add?

> Please describe what you want to add to the component. 

### How should it look like?

> Please add images. 

###  What did you do?

> Please replace this with what you did. 

### What did you expect to happen?

> Please replace this with what you expected to happen.  

### What happened instead?

> Please replace this with what happened instead.

### Your Environment

- Version of the component: _insert here_
- Swift version: _insert here_
- iOS version: _insert here_
- Device: _insert here_
- Xcode version: _insert here_
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by freaqed** [comment]
Hello, @mjpablo23. Looks like the problems is in your outlets. Can't tell you what exactly wrong because provided isn't enough. Closing issue as unrelated to lib.

**Comment by mjpablo23** [comment]
ok thanks.  yes, it was the outlets.  I fixed it by taking out the
connections for the overlayview to the storyboard, and doing it all
programatically.
