### ISSUE TITLE
Show white background when swapping is done then show the Image that is in stack

### ISSUE THREAD

**Issue by madBureaToT** [Yalantis/Koloda#301]
# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What do you want to add?

> Please describe what you want to add to the component. 

### How should it look like?

> Please add images. 

###  What did you do?

> Please replace this with what you did. 

### What did you expect to happen?

> Please replace this with what you expected to happen.  

### What happened instead?

> Please replace this with what happened instead.

### Your Environment

- Version of the component: _insert here_
- Swift version: _insert here_
- iOS version: _insert here_
- Device: _insert here_
- Xcode version: _insert here_
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by madBureaToT** [comment]
Actually i have used this library everything works perfect. but i need white background when swapping is done after some time it will show the image in curl animation .

**Comment by freaqed** [comment]
Hello, @madBureaToT! Please clean up issue template because right now it's not readable and I can't understand your problem.
