### ISSUE TITLE
Function didSwipeCardAt no working.

### ISSUE THREAD

**Issue by kyokyo123** [Yalantis/Koloda#303]
_#_ Report

> The more information you provide, the faster we can help you.

Hello, 
I've tired to using didSwipeCardAt function to receive what direction that user trigger.
But it don't enter the function even I set the breakpoint on it.

BTW, it works on original example project.
Same code move to my Test project  is failure.

Below project can reproduce the issue.
Please help me to figure out why.
Thanks.

> Please add a link to a project we can download that reproduces the bug.
https://github.com/kyokyo123/TestKoloda

**Comment by bgatewood** [comment]
I'm having a similar issue.  The delegate seems to be set correctly and didSelectCardAt works, but didSwipeCardAt is never called.  Here's my controller:

```
import UIKit
import Koloda

private var numberOfCards: Int = 5

class KolodaTestViewController: UIViewController {

    @IBOutlet weak var kolodaView: KolodaView!

    fileprivate var dataSource: [UIImage] = {
        var array: [UIImage] = []
        for index in 0..<numberOfCards {
            array.append(UIImage(named: "symptom-icon-bloody-lg")!)
        }
        
        return array
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        kolodaView.dataSource = self
        kolodaView.delegate = self
    }
}

// MARK: KolodaViewDelegate

extension KolodaTestViewController: KolodaViewDelegate {
    
    func kolodaDidRunOutOfCards(_ koloda: KolodaView) {
        kolodaView.reloadData()
    }
    
    func koloda(_ koloda: KolodaView, didSelectCardAt index: Int) {
        print("Selected \(index)") // this works
    }
    
    func koloda(koloda: KolodaView, didSwipeCardAt index: Int, in direction: SwipeResultDirection) {
        print("Swiped \(index) in \(direction)") // never called
    }
    
}

// MARK: KolodaViewDataSource

extension KolodaTestViewController: KolodaViewDataSource {
    
    func kolodaNumberOfCards(_ koloda: KolodaView) -> Int {
        return dataSource.count
    }
    
    func kolodaSpeedThatCardShouldDrag(_ koloda: KolodaView) -> DragSpeed {
        return .default
    }
    
    func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView {
        return UIImageView(image: dataSource[Int(index)])
    }
}
```

Any clues are much appreciated!

**Comment by freaqed** [comment]
Hi, @kyokyo123! I've just examined your code and it seems like the problem is in method declaration:
instead of `func koloda(koloda: KolodaView, didSwipeCardAt index: Int, in direction: SwipeResultDirection)` you have to use `func koloda(_ koloda: KolodaView, didSwipeCardAt index: Int, in direction: SwipeResultDirection)` (as declared in `KolodaViewDelegate`.
The same is true for @bgatewood.

**Comment by bgatewood** [comment]
Yes, thank you!  Oy.  That's a significant portion of my life I'll never get back.

**Comment by kyokyo123** [comment]
Hi @freaqed,
Thanks for your comment, it really solved my problem.
I also find the issue is cause I copy function from Read me file.  :)

**Comment by freaqed** [comment]
@kyokyo123
Yep, guys already pointed me. Sorry for that, will fix asap.
