### ISSUE TITLE
draggedCardWithPercentage not called

### ISSUE THREAD

**Issue by Geoffrey63** [Yalantis/Koloda#306]
# Report
###  What did you do?
I have added this method (in the Example project) : 
```
func koloda(koloda: KolodaView, draggedCardWithPercentage finishPercentage: CGFloat, in direction: SwipeResultDirection) {
        print(finishPercentage)
    } 
```
in `ViewController.swift`, below the `didSelectCardAt` method.

### What did you expect to happen?
Print the percentage in log

### What happened instead?
Nothing is printed in log 

### Your Environment

- Version of the component: 4.0
- Swift version: 4.0 
- iOS version: 
- Device: _insert here_
- Xcode version: _insert here_
- If you use Cocoapods: 

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.12.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5ecc2c6e2d7dfd0676c5079fceef4d15451a3664
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Koloda_Example' do
  pod "Koloda", :path => "../"
end

post_install do |installer|
  `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end
```

### Project that demonstrates the bug
Just add the the method in the sample project into `KolodaViewDelegate`
```
func koloda(koloda: KolodaView, draggedCardWithPercentage finishPercentage: CGFloat, in direction: SwipeResultDirection) {
        print(finishPercentage)
    }
```

**Comment by freaqed** [comment]
Hi, @Geoffrey63!
Looks like the problem is in method naming. Consider using `func koloda(_ koloda: KolodaView, draggedCardWithPercentage finishPercentage: CGFloat, in direction: SwipeResultDirection)`
