### ISSUE TITLE
video not playing

### ISSUE THREAD

**Issue by irshad9998** [Yalantis/Koloda#310]
Hello,

I want to play video on card

here is code 

` 
        func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView {

        print(index)
        //For Video
        let video_view = UIView(frame: CGRect(x: 0, y: 0, width: 300, height: 300))
        video_view.backgroundColor = UIColor.clear
        
        guard let path = Bundle.main.path(forResource: "\(index + 1)", ofType:"mp4") else {
            print("video not found")
            return video_view
        }
        player.pause()
        player = AVPlayer()
        player = AVPlayer(url: URL(fileURLWithPath: path))
        previewLayer = AVPlayerLayer(player: player)
        previewLayer.frame = video_view.bounds
        previewLayer.videoGravity = AVLayerVideoGravityResizeAspectFill
        video_view.layer.addSublayer(previewLayer)
        player.play()
        
        NotificationCenter.default.removeObserver(self, name: .AVPlayerItemDidPlayToEndTime, object: nil)
        NotificationCenter.default.addObserver(forName: .AVPlayerItemDidPlayToEndTime, object: player.currentItem, queue: nil, using: { _ in
            DispatchQueue.main.async {
                self.player.seek(to: kCMTimeZero)
                self.player.play()
            }
        })
        
        //For Boader and redius
        video_view.layer.cornerRadius = 8.0
        video_view.clipsToBounds = true
        
        video_view.layer.borderWidth = 6.0
        video_view.layer.borderColor = UIColor(colorLiteralRed: 98/255, green: 168/255, blue: 117/255, alpha: 1.0).cgColor
        
        return video_view
    }`

but it's not playing

**Comment by freaqed** [comment]
Hello, @irshad9998 
Reported issue isn't related to Koloda. Please feel free to ask your question on StackOverflow.
