### ISSUE TITLE
How to block vertical directions?

### ISSUE THREAD

**Issue by acalbuquerque** [Yalantis/Koloda#313]
I don't wanna allow the touch event for vertical direction. Even the bounce effect.
allowedDirectionsForIndex should have a param to not allow the bounce effect for others directions.

**Comment by ElChepa** [comment]
If you want to prevent the user from dragging the card vertically, you could do it yourself by editing the DraggableCardView class implemented by the koloda framework. You have to change the ".changed" case of the switch statement in the implementation of the "panGestureRecognized" method.

Change this: 
`transform = CATransform3DTranslate(transform, dragDistance.x, dragDistance.y, 0)`

To this: 
`transform = CATransform3DTranslate(transform, dragDistance.x, layer.anchorPoint.y, 0)`

Changing the "ty" parameter of the CATransform3DTranslate Method from dragDistance.y to layer.anchorPoint.y results in a card view never changing its y / height Position. Instead, it stays at its original anchorPoint y / height Position.

If you also want that the card view always rotates to the left or right bottom you also have to change the value of the "animationDirectionY" property in the .began case of the same switch statement.

From this: 
`animationDirectionY = touchLocation.y >= frame.size.height / 2 ? -1.0 : 1.0`

To this: 
`animationDirectionY = 1`
