### ISSUE TITLE
Disable card swiping once card has been tapped

### ISSUE THREAD

**Issue by hallamager** [Yalantis/Koloda#315]
Hi,

I was wondering if it would be possible to disable any card swiping once the top card has been tapped.

Thanks

**Comment by jmejiaa** [comment]
Can you try setting userInteractionEnabled = false when the user taps the card (didTapCard)?

**Comment by hallamager** [comment]
Thanks for the reply. That does work but not quite in the way I want it to. Basically, when I tap on the card I've added a flip transition to another nib file. The nib file has a scrollView within so when userinteraction is false it also disables any interaction with the scrollView. The same problem occurs with the swiping as it overrides the scrollView. Not sure how to get around this?

**Comment by jmejiaa** [comment]
Try implementing these in your KolodaViewDelegate

```
func koloda(_ koloda: KolodaView, shouldSwipeCardAt index: Int, in direction: SwipeResultDirection) -> Bool {
        return false
    }

    func koloda(_ koloda: KolodaView, shouldDragCardAt index: Int ) -> Bool {
        return false
    }
```

**Comment by hallamager** [comment]
These work great, but I want the shouldDragCardAt to only happen once a user has tapped the card. I've tried putting that func inside the didSelectCardAt func put that doesn't work.
