### ISSUE TITLE
Position of cards problem in iOS 11

### ISSUE THREAD

**Issue by SomnusDN** [Yalantis/Koloda#316]
![Uploading 屏幕快照 2017-09-19 上午11.40.23.png…]()
Position offset of cards in iOS 11

**Comment by Sethu171988** [comment]
I am also having the same issue here... Managed to fix it?

**Comment by alexgoodison** [comment]
Have a look at #295

**Comment by Sethu171988** [comment]
Yes that solved the issue for the time being

**Comment by SomnusDN** [comment]
Thank you very much，your koloda framework is great👍

发自我的 iPhone

> 在 2017年9月21日，上午12:57，Sethuraghavan <notifications@github.com> 写道：
> 
> Yes that solved the issue for the time being
>

**Comment by freaqed** [comment]
Closed along with #295. Thanks for reporting!

**Comment by SomnusDN** [comment]
Thank you very much for taking the time to solve this problem, your koloda framework is really great, I really like, I also recommend to the side of the development of this framework, I use your frame when the card slide direction is used up and down two directions, but I found that when the card left and right to slide to a certain value will fly away, you can see here can be optimized, there are some of the sensitive in the slide, the experience will be better, some small suggestions, please understand.Thank you so much.
