### ISSUE TITLE
In IOS 11 overly images changed and looks bad! what should I do?

### ISSUE THREAD

**Issue by HamedGh** [Yalantis/Koloda#318]
The Images are not center vertically.

<img width="398" alt="screen shot 1396-06-29 at 14 31 04" src="https://user-images.githubusercontent.com/3388482/30638351-65f36e28-9e10-11e7-8b82-71f9254e374d.png">

ios 11
swift 3
iphone 6s - iphone x
xcode 9
added with pod

**Comment by alexgoodison** [comment]
Also having this issue. Any solution?

**Comment by freaqed** [comment]
Closed along with #295. Thanks for reporting!
