### ISSUE TITLE
Cant install Koloda v 4.3 via CocoaPods

### ISSUE THREAD

**Issue by SebastianKumor** [Yalantis/Koloda#322]
# Report

This is the message I get when I try to update with cocoapods
[!] Unable to satisfy the following requirements:

- `Koloda (~> 4.3)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Koloda (~> 4.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

###  What did you do?

updatet Koloda in podfile to 4.3
### What did you expect to happen?

Update cocoapod for xcode 9 and swift 4
### What happened instead?

cocoapods instalation failed
### Your Environment

- Version of the component: running version 4.1
- Swift version: _insert here_ 3.2 trying to update to 4
- iOS version: 11
- Device: -
- Xcode version: 9.0 
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 

CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1375149af874e31e6fa6fd3e7376a26781d6536d
               twilio - https://github.com/twilio/cocoapod-specs @ f3f861ed4b4b0bccd161e76d6d54bddbbd1e124a
### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by freaqed** [comment]
Hi, @SebastianKumor!
We've fixed that issue. Thanks for reporting and sorry for the inconvenience!

**Comment by SebastianKumor** [comment]
@freaqed thanks for quick fix  :)
