### ISSUE TITLE
After swiping all the cards how to reload the card view again.

### ISSUE THREAD

**Issue by osvin-ios** [Yalantis/Koloda#327]
# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

After swiping all the cards how to reload the card view again.

> Please describe what you want to add to the component. 

func kolodaDidRunOutOfCards(_ koloda: KolodaView) {
        
        koloda.reloadData()

    }
    
    func koloda(_ koloda: KolodaView, didSwipeCardAt index: Int, in direction: SwipeResultDirection) {
        
//        if self.array_eventList.count - index < 3 {
//            self.reloadEventList()
//        }
        
    }

> Please add images. 

 How to reload the Koloda Card view. As am not able to reload the data like we do in table view or in collection view. koloda.reloadData(). This lines do nothing.

> Please replace this with what you did. 

How to reload all the card view

> Please replace this with what you expected to happen.  

How to reload all the card view

> Please replace this with what happened instead.

### Your Environment

  pod 'Koloda', '~> 4.0'

> Please add a link to a project we can download that reproduces the bug.

**Comment by crehbichler** [comment]
You can use koloda.resetCurrentCardIndex(), which clears the currentCardIndex and then calls reloadData internally.
