### ISSUE TITLE
Custom View don't show subvieviews 

### ISSUE THREAD

**Issue by dragmar007** [Yalantis/Koloda#329]
HI all, Koloda is a great Framework!! Thank you for building it. 
But I have the following issue:
I've built a custom UIView to show up as a card. Inside the View I have a UiimageView, and a Label. 
But the cards are invisible except if I set a backroundimage for the custom View itself AND 
only the last card in the deck will appear with the correct subviews...

Edit: If I return a simple UIImageView (like in the example Project) everything works fine.
So there must something be wrong within returning a custom UIView.

Infos: Xcode 9, swift 3
OS: IOS 11

Here are some Screen Shots: 

**Loaded Deck with Custom View:**

![simulator screen shot - iphone se - 2017-10-19 at 14 33 29](https://user-images.githubusercontent.com/32930883/31771013-ba390642-b4da-11e7-81b6-8983133593a6.png)

**Last Card of Deck with UIimage view.. correct appearance:**

![simulator screen shot - iphone se - 2017-10-19 at 14 33 41](https://user-images.githubusercontent.com/32930883/31771034-d25e865c-b4da-11e7-9d70-803cbfcd490c.png)

**Here is the Code of my Custom View:**
```
import UIKit

let image1: CustomImageView = {
   let image = CustomImageView()
    image.contentMode = .scaleAspectFit
    image.backgroundColor = UIColor.white
    image.image = #imageLiteral(resourceName: "unknownu")
    return image
}()

let label: UILabel = {
   let label = UILabel()
    label.backgroundColor = UIColor.white
    return label
}()
let topview: UIView = {
   let topview = UIView()
    topview.backgroundColor = UIColor.white
    return topview
}()

class eventCardView: UIView{
 
    override init(frame: CGRect) {
        super.init(frame: frame)
        addSubview(image1)
        image1.frame = CGRect(x: 0, y: 0, width: 100, height: 100)


    }  
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```
**Here my view for card:**
```
  func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView{
        let customView = eventCardView()
        customView.backgroundColor = UIColor.blue
        return customView
        }
```
Thank you in advance

**Comment by freaqed** [comment]
Hi, @dragmar007!
I've just checked usage of custom view and everything works fine
Your problem is related to either layouting or view instantiating.
Closing as not related to Koloda component
