### ISSUE TITLE
Not loading all cards

### ISSUE THREAD

**Issue by alexgoodison** [Yalantis/Koloda#332]
![simulator screen shot 31 oct 2017 21 37 48](https://user-images.githubusercontent.com/17804268/32274678-d439b1fc-beff-11e7-8034-3398c49e9b8f.png)

Each article image and title should be loading into the KolodaView but in this case where there should be 60 articles, only one has shown and I can't swipe on it. Any help apprecaited

**Comment by freaqed** [comment]
Hello, @alexgoodison 
Please share with us your code of the Koloda usage.

**Comment by rnkyr** [comment]
Closing as outdated. Let us know if you still facing an issue
