### ISSUE TITLE
It seems your data source called twice 

### ISSUE THREAD

**Issue by burkaslarry** [Yalantis/Koloda#334]
I have create an object list in your module and test. it founds : 

func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView {
        print("A index :\(index)")
        return UIImageView(image: UIImage(named: dataSource[index].thumbNail))
    }
    
    func koloda(_ koloda: KolodaView, viewForCardOverlayAt index: Int) -> OverlayView? {
        print("B index :\(index)")
        lblTextCompany.text = dataSource[index].engName
        return Bundle.main.loadNibNamed("CustomOverlayView", owner: self, options: nil)?[0] as? OverlayView
    }

being called twice. 

A index :1
B index :1
A index :2
B index :2

**Comment by burkaslarry** [comment]
Using  kolodaView.currentCardIndex  to get the current object, kolodaView.currentCardIndex  seems not updating while swipping the last item

**Comment by freaqed** [comment]
Hello, @burkaslarry!
You're right, Koloda is calling `koloda(_:viewForCardAt:)` and few more method for currently visible and the next card. So once you're reloaded data, it's called for two cards. If you swipe it'll be called once (for the next card). This is how it works and it allows to provide smooth animation while changing cards. It's not an issue
