### ISSUE TITLE
manual swipe has a lag

### ISSUE THREAD

**Issue by localsDeveloper** [Yalantis/Koloda#336]
I still have a dragging issue. Does anyone else get laggy swiping when dragging the card? At the moment the threshold is reached, the animation starts but it is not smooth. The swipe by button tap is flawless and fast though.

I load data from backend (image and a few other properties) to fill the cards.

**Comment by SerjOxo** [comment]
@localsDeveloper Hello! Thank you for report. It seems that you start loading data from backend at `func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView`. If you want smoother drag animation you should fetch data before the filling of your card begins.

**Comment by localsDeveloper** [comment]
No, I load backend data in viewDidLoad and trigger reloadData on completion.

**Comment by SerjOxo** [comment]
@localsDeveloper, Maybe you have something that is executed in the main thread when dragging?

**Comment by localsDeveloper** [comment]
I think I managed it by using background threads for expensive Google tasks. Seems to drag more or less smoothly.
