### ISSUE TITLE
Playing videos in cards

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Yalantis/Koloda#338]
Hi,

I have to play a bunch of videos retrieved from the internet on cards. This is my view generator.

```swift
func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView {
    let containerView = UIView(frame: self.view.bounds)
    let asset = AVURLAsset(url: URL(string: urls[index])!)
    asset.resourceLoader.setDelegate(self, queue: DispatchQueue.main)
    
    let player = AVPlayer(playerItem: AVPlayerItem(asset: asset))
    player.actionAtItemEnd = .none
    
    let playerLayer = AVPlayerLayer(player: player)
    playerLayer.frame = self.view.bounds
    playerLayer.backgroundColor = UIColor.clear.cgColor
    
    containerView.layer.addSublayer(playerLayer)
    
    player.play()
    return containerView
}
```

I see that `viewForCardAt` gets called for the card that's behind the currently displayed card. So the problem is when I start playing the video in this method, the video in the next card also starts playing. 

Is there a way in Koloda to work around this?

I also attached a demo project [here](https://www.dropbox.com/s/hz19i05g9oeaqa3/KolodaVideo.zip?dl=0).

**Comment by SerjOxo** [comment]
@Isuru-Nanayakkara, Hi! You can solve it by creating own subclass of UIView with AVPlayer property. Then, in `func koloda(_ koloda: KolodaView, didShowCardAt index: Int)` you can get current visible card by using `koloda.viewForCard(at: index)` and start playing the video.
