### ISSUE TITLE
Cards behind don't have their own data when using a UICollectionView

### ISSUE THREAD

**Issue by mteera** [Yalantis/Koloda#339]
I am able to get my UICollectionView to work with Koloda, however it seems that the 2 visible cards that are stacked is only displaying data from the initial card until the it becomes the current card. So when you are swiping it you see a duplicate.

Here is a screenshot of an example of my project. It is displaying the same data behind it. And only after I swipe it does the current card update, but then the card behind it also is the same.

<img width="540" alt="screen shot 2017-11-21 at 16 33 38" src="https://user-images.githubusercontent.com/11030764/33084445-e8d91186-ced9-11e7-9251-45b57a4f2180.png">

**Comment by freaqed** [comment]
@mteera, did you solve your issue?
If not please tell us more about how you're using `Koloda` and what `UICollectionView` doing here.
If you could share your code it would help to resolve the issue much faster.
