### ISSUE TITLE
Card unresponsive when it is animating back to the center

### ISSUE THREAD

**Issue by carbocation** [Yalantis/Koloda#34]
Currently, when the user drags a card a short way and releases, the card animates back to the center. During this reset animation, the user cannot interact with the card. This can be frustrating to the user because the app feels (and, in fact, is) unresponsive during this time.

Due to this, I have created a proposed change ( #33 ) that allows users to interact with the card as soon as it is released, even if it is still animating. There may be better approaches, however.

**Comment by AEugene** [comment]
Fixed with #33
