### ISSUE TITLE
Error in fetch version 4.3.1 using Carthage

### ISSUE THREAD

**Issue by ujamshy** [Yalantis/Koloda#342]
## Report a bug
Tried to fetch version 4.3.1 using carthage but got an error.

###  What did you do?
Relevant line in Cartfile:
github "Yalantis/Koloda" ~> 4.3.1

invoked:
$ carthage update koloda

### What did you expect to happen?

Expected Koloda version 4.3.1 to be downloaded and compiled.

### What happened instead?

Got error:
No available version for github "Yalantis/Koloda" satisfies the requirement: ~> 4.3.1

### Your Environment

- Version of the component:  4.3.1
- Swift version: NA
- iOS version: NA
- Device: NA
- Xcode version: NA
- If you use Carthage: _run `carthage version | pbcopy` and insert here: 0.26.2

### More info

When trying with version 4.0 everything works as expected.
Tried to uninstall/reinstall Carthage - problem still remains.

**Comment by SerjOxo** [comment]
@ujamshy Hi, thanks for your report. I checked your issue but this Cartfile configuration works fine. Try to update Carthage to latest version.

**Comment by freaqed** [comment]
@ujamshy, if you still reproduce the problem feel free to reopen an issue
