### ISSUE TITLE
Scrolling UIWebView as UIView within KolodaView

### ISSUE THREAD

**Issue by PetroShylaiev** [Yalantis/Koloda#343]
Hi! 

Thanks for your awesome library!

I do use UIWebView instances as UIView's within KolodaView. There can be a various of different web sites. Some of them open "burger menu" with the swipe from left to right and block KolodaView swipe gesture. As a result we have a gesture recognizers collision. 

How can we deal with it?

**Comment by freaqed** [comment]
Hello, @PetroShylaiev!
KolodaView doesn't support internal scrolling. I don't think it's a good idea to use webview inside any collection since it's pretty expensive component.
Closing issue as not related to Koloda component.
