### ISSUE TITLE
Flickering upon first load

### ISSUE THREAD

**Issue by marcospolanco** [Yalantis/Koloda#347]
## A feature request

When first loading the images, the ones to be shown post-swipe of the top of the stack briefly flicker on the screen. 

> Please describe what you want to add to the component. 

There should be a way to stack up the images upon first loading while keeping them from appearing to the user at all.

**Comment by freaqed** [comment]
Hi, @marcospolanco!
The problem you describe seems to be related to image loading. Could you share the code so I can investigate it?
