### ISSUE TITLE
EXC_BAD_ACCESS on Swift 2.0

### ISSUE THREAD

**Issue by erikwennerberg** [Yalantis/Koloda#35]
Dear Yalantis,

I'm using Swift 2.0 + Xcode 7.0 GM seed, with the swift2.0 branch of Koloda.
I get an EXC_BAD_ACCESS error for:
        self.kolodaView.dataSource = self
        self.kolodaView.delegate = self

Here is a screenshot:
<img width="825" alt="screen shot 2015-09-16 at 4 07 55 pm" src="https://cloud.githubusercontent.com/assets/1062453/9917012/6c822598-5c8d-11e5-8c73-7e18934ac284.png">

Thanks!

Erik

**Comment by RayanSaeed** [comment]
Did you find any solution to this?
I'm having the same issue

**Comment by Bashta** [comment]
Had the same problem. Resolved by selecting the kolodaView in interface builder then in the identity inspector set the Class of the view to "KolodaView" and the Module to "Koloda"

**Comment by RayanSaeed** [comment]
@Bashta Did u get into the problem where the delegate is not set?

**Comment by Bashta** [comment]
I have not such a problem. I am setting the delegate in code and all the delegate methods are being called properly.

**Comment by RayanSaeed** [comment]
@Bashta Can you please have a look at my code and project quickly?? 5 minutes maybe??

**Comment by Bashta** [comment]
This is not the appropriate place.

**Comment by AEugene** [comment]
I updated Koloda repository to proper Swift 2.0 integration. I checked last version and there is no issues like this.

**Comment by Bashta** [comment]
Thank you will give it a try asap as i am currently using Koloda in one of my projects.

**Comment by RayanSaeed** [comment]
@AEugene  I just did "pod update" on my project and after a build..  This is what I'm getting

<img width="258" alt="screen shot 2015-09-21 at 4 06 49 pm" src="https://cloud.githubusercontent.com/assets/8598858/9990452/dc908afa-607a-11e5-8dfd-5583dfef3e60.png">

**Comment by RayanSaeed** [comment]
@AEugene I'm using Xcode 6.4 and OS X El Capitan.... Which version of Koloda should I be using?

**Comment by RayanSaeed** [comment]
@AEugene I want to use it with Xcode 6.4 and iOS 8.. Can you please suggest me which version should I use of koloda??? Should I 

pod 'Koloda', '~> 1.1.2'

**Comment by Bashta** [comment]
Working fine on 7.0!  Thank you a lot!

**Comment by RayanSaeed** [comment]
kolodaView.delegate = self

I have this line very clearly and 100% surely in my code.. But still the delegate methods are not getting called. Why is that?????

**Comment by AEugene** [comment]
1) Check outlets
2) Check the delegate methods
You can see example in repository

**Comment by RayanSaeed** [comment]
1) Outlets checked.. Like literally a million times... The cards are showing up, so the dataSource is connected. But delegate methods are not getting called...

2) I've added println() statements inside this function
    func cardTapped(card: DraggableCardView) {
        let index = currentCardNumber + find(visibleCards, card)!
        println("The card was tapped and delegate is \(delegate)"
        delegate?.kolodaDidSelectCardAtIndex(self, index: UInt(index))
    }


and this is what prints out when I tap the card.. "The card was tapped and delegate is nil"

**Comment by RayanSaeed** [comment]
@AEugene I will be really thankful. If you could just just take out 5 minutes. Please

**Comment by RayanSaeed** [comment]
@AEugene I've attached a screenshot in the last comment also..  I will be really thankful. If you could just just take out 5 minutes. Please

**Comment by AEugene** [comment]
@RayanSaeed Issues should be fixed with #41

**Comment by RayanSaeed** [comment]
@AEugene Okay.. That's good but actually I'm using Xcode 6.4 as of now, and can't update to Koloda 2.0.0.... So can you please suggest me what to do now?? or how can I update my project so that this issue is fixed and project doesn't break...

**Comment by AEugene** [comment]
@RayanSaeed I didn't encounter this issue on versions for swift 1.2. And you're writing in unrelated to your issue thread.

**Comment by RayanSaeed** [comment]
@AEugene So should I create another issue for this?? Will you reply there?? Because I don't know if I'll get hold of someone from Yalantis because you can understand and solve my problem like no one else...

**Comment by Kourghan** [comment]
Hello @RayanSaed! 
Yes, it's better to create another issue for your problem.
However soon we are going to drop support issues on swift version under 2.0 (starting from Xcode 7.0).

**Comment by RayanSaeed** [comment]
@Kourghan Okay then actually I'm already downloading Xcode 7 (1.64/3.59GB done). 

But can you help me with #40 ??

**Comment by Kourghan** [comment]
@RayanSaeed Sure, I'll check it. 
Closing this one.
