### ISSUE TITLE
How to remove background animation?

### ISSUE THREAD

**Issue by Chimdi511** [Yalantis/Koloda#350]
I want to remove the background animation, but I can't find any documentation on the kolodaBackgroundCardAnimation delegate function. How do I do this?

**Comment by freaqed** [comment]
Hello, @Chimdi511!
What exactly you mean by "background animation"?

**Comment by freaqed** [comment]
Ok, I probably figured your question. Please take a look at example project, specifically `ViewController.swift`. It doesn't use any background animator. Feel free to reopen if it doesn't help
