### ISSUE TITLE
Fixed X and Y?

### ISSUE THREAD

**Issue by mcinside13** [Yalantis/Koloda#352]
Its possible to fixed X or Y position when swipe the card?

e.g: when i swipe the card for right and left, the card not swipe to top nor bottom.

**Comment by freaqed** [comment]
Hi, @mcinside13!
Currently, Koloda doesn't support such behavior. 
Feel free to change it by yourself and open PR. Looks like `DraggableCardView.panGestureRecognized(_:)` is the method you need to tweak.
