### ISSUE TITLE
 how to add other view ,images and label on Koloda view which also able to and change it's content swipe.

### ISSUE THREAD

**Issue by pritam0605** [Yalantis/Koloda#355]
I want too implement some project where I use tinder like swipe . I use https://github.com/Yalantis/Koloda 
but can't understand how to add other view and images and label on Koloda view which also able to and change it's content swipe.

**Comment by freaqed** [comment]
Hello, @pritam0605!
Please take a look at the Example project. It contains two ViewControllers which implements KolodaView support. You can find there examples of customized cells as well
