### ISSUE TITLE
Koloda no longer recognizes taps when ShouldDragCardAt set to false

### ISSUE THREAD

**Issue by nickschafhauser** [Yalantis/Koloda#356]
Once I set 
func koloda(_ kolodaTemp: KolodaView, shouldDragCardAt index: Int) -> Bool {
        return false
}
so that the user could no longer move the cards around, Koloda no longer recognizes when a user taps on that card. I would still like that functionality.
The protocol I am using to recognize taps on the card is
 func koloda(_ koloda: KolodaView, didSelectCardAt index: Int) {
       //Do something with that card
}
Is there a way around this issue? Thanks.

**Comment by freaqed** [comment]
fixed via #360. will be available soon
