### ISSUE TITLE
Button inside kolodaview not responding

### ISSUE THREAD

**Issue by cvindhani** [Yalantis/Koloda#359]
Hi
First of all thanks for creating such beautiful control. It's makes my life easier.

I'm using one custom view with XIB. Inside that there are lots of controls I'm using, I have put UIButton inside custom view. But when I'm placing that custom view inside the koloda view for swiping, button is not responding. I have already remove overlay by using koloda(_ koloda: KolodaView, viewForCardOverlayAt index: Int) -> OverlayView? method. I tried so many ways but I'm not getting button event from custom view.

Please provide me a solution for that.

Thanks in advance.

**Comment by cvindhani** [comment]
Sorry for posting issue. I got the solution as the issue is persist because of my mistake. 
Thanks :)

**Comment by iPhonig** [comment]
what was your solution? I'm facing a similar problem
