### ISSUE TITLE
Feature Request: kolodaViewCard:isDraggingInDirection:

### ISSUE THREAD

**Issue by skram** [Yalantis/Koloda#36]
Love the framework. My only suggestion is, there should be a way to know which way a card is being dragged. This would allow greater integration in a UI, i,e: I can show specific UI elements based on if the user is dragging to the left as opposed to the right. If someone could implement that and do a pull request would be great.

**Comment by AEugene** [comment]
We may implement it in next versions.

**Comment by AEugene** [comment]
Fixed with #48
