### ISSUE TITLE
Swipe Left

### ISSUE THREAD

**Issue by MaurixFx** [Yalantis/Koloda#364]
Hello Guys. Thanks for the amazing Job, please your help with these. How I can when swipe left get back previous image?.

Regards
Mauricio

**Comment by SerjOxo** [comment]
@MaurixFx Hi! You can always ask your question at [StackOverflow](https://stackoverflow.com) (see [contributing guide](https://github.com/Yalantis/Koloda/blob/master/.github/contributing.md))
