### ISSUE TITLE
add multiple image in single view

### ISSUE THREAD

**Issue by prashantdabhi9033** [Yalantis/Koloda#370]
# Report

> The more information you provide, the faster we can help you.

## A feature request
i already used koloda view and its very smooth in use but now my requiremnt is change. i want to add multiple images in single view like tinder when user click on image then next image will display for same card.

> Please describe what you want to add to the component. 

###  What did you do?
i try to add page controll in custom view but not able to do achive what i want
  

### Your Environment

- Version of the component: _insert here_
- Swift version: _4.1_
- iOS version: _ios11_
- Device: _insert here_
- Xcode version: _insert here_
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by prashantdabhi9033** [comment]
i solve this using collection view in custom view and add page controll into cuatom view. but now i want to create animation while revert card. if i swipe left and then clcik on revert action then it animate from left to center. is there anything to achive this?

**Comment by SaurabhZorang** [comment]
## You can create a custom view and add imagviews to it and load this custom view inside 
 ``` koloda(_:viewForCardAt:)```

**Comment by Obi-codes** [comment]
> i solve this using collection view in custom view and add page controll into cuatom view. but now i want to create animation while revert card. if i swipe left and then clcik on revert action then it animate from left to center. is there anything to achive this?

prash could you show me how
