### ISSUE TITLE
more function for revertAction()

### ISSUE THREAD

**Issue by kohdesmond** [Yalantis/Koloda#371]
# Report

> The more information you provide, the faster we can help you.

###  What do you want to add?
revertAction()
allow disable or allow faster animation

### How should it look like?

> Please add images. 

> Please replace this with what you did. 

### What did you expect to happen?

> Please replace this with what you expected to happen.  

### What happened instead?

> Please replace this with what happened instead.

### Your Environment

- Version of the component: 'Koloda', '~> 4.3.1'
- Swift version: 4.x
- iOS version: iOS 11
- Device: _insert here_
- Xcode version: 9.3 (9E145)
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by rnkyr** [comment]
hey, @kohdesmond
the latest version of the Koloda includes an ability to revert in any direction. it also now possible to change default timing properties
