### ISSUE TITLE
Problem when ScrollingCardView used in viewForCardAt

### ISSUE THREAD

**Issue by asikand-view** [Yalantis/Koloda#372]
I'm using https://github.com/mozilla-mobile/ScrollingCardView as the View in the viewForCardAt method. But instead of scrolling like by dragging up and down on the card (like ScrollingCardView), it moves around the screen like a default Koloda draggable card. How do I get the scrolling functionality back? I'll buy you guys a coffee if you help me out. Love the UI work.

Thanks,
Alex

**Comment by rnkyr** [comment]
KolodaView uses gestures to be able to pan/touch its view. You can control somehow with the help of appropriate delegate methods. it wasn't supposed to be used like that
