### ISSUE TITLE
Infinite loop through cards while not reducing number of visible cards.

### ISSUE THREAD

**Issue by ashinasok** [Yalantis/Koloda#374]
Tried to implement infinite loop of cards while keeping the number of visible cards as 4. 

Issue:

if the number of visible cards is 4 and total number of cards is also 4 . So whenever currentCardIndex reaches 1 the number of visible cards reduces to 3 and so on . When the last card in this case 4th card is swiped there is a blank screen and the card list is reloaded .

My current requirement is that the number of visible cards or background cards remain the same but the card stack loop is infinite.

Code used to reload card:
`
func kolodaDidRunOutOfCards(_ koloda: KolodaView) {
        kolodaView.resetCurrentCardIndex()
        kolodaView.revertAction()
    }
`

### Your Environment

- Version of the component: 4.3.1
- Swift version: 4.1
- iOS version: iOS 10
- Device: iPad & iPhone
- Xcode version: 9.4

**Comment by ashinasok** [comment]
Sample code:

` @IBOutlet weak var kolodaView: KolodaView!
    
    let colors    = [
                        "#FFFF00" ,
                        "#000000" ,
                        "#FF0000" ,
                        "#00FF00"
                    ]
    
    
    func hexStringToUIColor (hex:String) -> UIColor {
        var cString:String = hex.trimmingCharacters(in: .whitespacesAndNewlines).uppercased()
        
        if (cString.hasPrefix("#")) {
            cString.remove(at: cString.startIndex)
        }
        
        if ((cString.count) != 6) {
            return UIColor.gray
        }
        
        var rgbValue:UInt32 = 0
        Scanner(string: cString).scanHexInt32(&rgbValue)
        
        return UIColor(
            red: CGFloat((rgbValue & 0xFF0000) >> 16) / 255.0,
            green: CGFloat((rgbValue & 0x00FF00) >> 8) / 255.0,
            blue: CGFloat(rgbValue & 0x0000FF) / 255.0,
            alpha: CGFloat(1.0)
        )
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        kolodaView.countOfVisibleCards = 4
        kolodaView.dataSource = self
        kolodaView.delegate = self
       
        self.modalTransitionStyle = UIModalTransitionStyle.flipHorizontal
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}

extension ViewController: KolodaViewDelegate {
    
    func kolodaDidRunOutOfCards(_ koloda: KolodaView) {
        kolodaView.resetCurrentCardIndex()
        kolodaView.revertAction()
    }
    
    func koloda(_ koloda: KolodaView, didSelectCardAt index: Int) {
        UIApplication.shared.openURL(URL(string: "https://yalantis.com/")!)
    }
    
    func kolodaShouldApplyAppearAnimation(_ koloda: KolodaView) -> Bool{
        return false
    }
    
}

// MARK: KolodaViewDataSource

extension ViewController: KolodaViewDataSource {
    
    
    func kolodaNumberOfCards(_ koloda: KolodaView) -> Int {
        return colors.count
    }
    
    func kolodaSpeedThatCardShouldDrag(_ koloda: KolodaView) -> DragSpeed {
        return .default
    }
    
    func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView {
        let viewBg = UIView()
        viewBg.backgroundColor = hexStringToUIColor(hex: colors[Int(index)])
        return viewBg
    }
    
    func koloda(_ koloda: KolodaView, viewForCardOverlayAt index: Int) -> OverlayView? {
        return Bundle.main.loadNibNamed("OverlayView", owner: self, options: nil)?[0] as? OverlayView
    }
}`

**Comment by keyhan76** [comment]
Hi,
Could you fix the problem?
Because have the same problem here and I'm searching for an answer.

**Comment by xradeon** [comment]
This should be closed. Already has built in functionality for infinite loop.

        kolodaView.isLoop = true

**Comment by rnkyr** [comment]
fixed via #357
