### ISSUE TITLE
Card inserted below top card is opaque even if shouldTransparentizeNextCard == true

### ISSUE THREAD

**Issue by bwhtmn** [Yalantis/Koloda#375]
When inserting a visible card below the top card, that newly inserted card is opaque after insertion, even if the shouldTransparentizeNextCard property is true.

###  What did you do?

Inserted a visible card.

### What did you expect to happen?

After insertion, if the card is not at the top and the KolodaView's shouldTransparentizeNextCard is true, the card should be semi-transparent

### What happened instead?

After insertion the card was opaque.

### Your Environment

- Version of the component: 4.3.1, also present in 4.3.2
- Swift version: 4.2
- iOS version: 11.4
- Device: iPhone X
- Xcode version: 9.4.1

### Project that demonstrates the bug

This issue can be seen in the Koloda example project:
1. Tap the button in top left to switch to the example with shows
2. Swipe through all the cards until you reach the bottom and the stack reloads
3. Note that all cards are opaque, even the bottom two.

**Comment by rnkyr** [comment]
Hi, @bwhtmn!
Thanks for figuring out this issue!
