### ISSUE TITLE
Sudo Swipe from some other function

### ISSUE THREAD

**Issue by yatindma** [Yalantis/Koloda#379]
###  What do you want to add?
to swipe Koloda Card from some other function without exactly swiping it right 

> Please describe what you want to add to the component. 
I want to integrate it with voice command but no function to swipe it without touching the screen 

### How should it look like?
with swiping animation will look good  and speed of swipe should be user define

**Comment by rnkyr** [comment]
hey, @yatindma

I don't get what you're asking for :)

basically, KolodaView got two options - swipe right or left. Both these options translated into appropriate actions.
