### ISSUE TITLE
Method to reload current card UI without starting from the first card again

### ISSUE THREAD

**Issue by mding5692** [Yalantis/Koloda#385]
# Report
###  What do you want to add?
When I use reloadData() to reload the UI, sometimes the card viewForCardAt method isnt actually called, but when I use resetCurrentCardIndex(), it starts from the first card again, was wondering if there was a method to just reload the card UI for the card right now. 

If not, I just made a temporary one for myself that other people can refer to, cos I tried the other ones in other issues but couldnt make it work:

func reloadCurrentCardUI() {
              let countableRange: CountableRange<Int> = self.currentCardIndex..<self.currentCardIndex+1
             self.reloadCardsInIndexRange(countableRange)
  }

**Comment by cresouls** [comment]
@mding5692 hope this helps

var data: [Any]! //data to be displayed in kolodaView

func kolodaDidRunOutOfCards(_ koloda: KolodaView) {
        data = data.shuffled()
        kolodaView.resetCurrentCardIndex()
  }

**Comment by mding5692** [comment]
@cresouls is kolodaDidRunOutOfCards(_) called whenever reloadData() or resetCurrentCardIndex() is called? Been a while that I touched Koloda API so not sure what the above does

**Comment by cresouls** [comment]
@mding5692 nope. kolodaDidRunOutOfCards(_) will be called when all the cards are finished swiping.

**Comment by rnkyr** [comment]
hey, @mding5692
this is possible with `reloadCardsInIndexRange` method (as you've already found)
it's public, as well as `currentCardIndex`. so you could easily create an extension for `KolodaView` with a convenient method
