### ISSUE TITLE
Card Blinks after update

### ISSUE THREAD

**Issue by Messa25** [Yalantis/Koloda#386]
First of all thank you for this perfect library, it is something amazing.

But in the light of last events, I mean updates I have noticed a blink on the card when swiping left or right. Please see the comments below. Thank you for paying attention to.

## Report a bug

The card blinks when swiping left or right. In can be exactly seen when having the overlay view

This issue started happening after update into version 4.5

The issue does not exist in version 4.3

###  What did you do?

Try to swipe left or right. 

### What did you expect to happen?

The card should be swiped left or right without any blink as it was in previous versions.

### Your Environment
- Version of the component: 4.5
- iOS version: 12 this issue can be observed on iOS 11  also
- Device:  Iphone X, iPhone 7
- Xcode version: 10
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

The issue can also be observed in you example project.

Please see the video attached (I would recommend you to set the speed to 0.5 on video player)
https://www.dropbox.com/sh/9eocbcngf1mdyfs/AABZ7Ln92qIYSGb06335rPJda?dl=0

**Comment by Messa25** [comment]
Hello guys, any updates on this issue?

**Comment by Ikloo** [comment]
Hi!
It's a really bad bug. I can provide a video with blinking every card if needed.
It's blinked if fast drag card to screen margins.

**Comment by rnkyr** [comment]
hello!
I've checked the diff for these (4.5 and 4.3) versions. I don't think it's something introduced with any code base changes since nothing related to frame/dragging changed. the only major update is migration between swift 3.2 and 4.0
I'll dig into it. meanwhile, if somebody has any thoughts on that issue let me know

**Comment by liriz002** [comment]
Hey there,

I'm getting the same blinking on my end. Have you been able to check it out? Or has anyone been able to fix it?

**Comment by sachithamh** [comment]
first time when card swipe its blink any fix  :(

**Comment by rnkyr** [comment]
closed via #409
