### ISSUE TITLE
EXC_BAD_INSTRUCTION (Xcode 6.4, El Capitan)

### ISSUE THREAD

**Issue by RayanSaeed** [Yalantis/Koloda#39]
Dear Yalantis,

I'm using Xcode 6.4.
I get an EXC_BAD_INSTRUCTION error for:
self.kolodaView.dataSource = self
self.kolodaView.delegate = self

Here is a screenshot:

<img width="1417" alt="screen shot 2015-09-21 at 8 34 37 am" src="https://cloud.githubusercontent.com/assets/8598858/9984952/cc2c839c-603b-11e5-999d-cc85b16a7525.png">

Thanks!
Rayan

**Comment by Bashta** [comment]
Solution to the above issue.
Had the same problem. Resolved by selecting the kolodaView in interface builder then in the identity inspector set the Class of the view to "KolodaView" and the Module to "Koloda"
