### ISSUE TITLE
Module compiled with Swift 4.0.2 cannot be imported by the Swift 4.2 compiler: /Users/xxx/Documents/hs-app-ios/xxx/build/Build/Products/Debug-iphonesimulator/Koloda/Koloda.framework/Modules/Koloda.swiftmodule/x86_64.swiftmodule

### ISSUE THREAD

**Issue by pawanhopscotch** [Yalantis/Koloda#391]
Koloda version is 4.1

**Comment by kaeferfreund** [comment]
Same here, having trouble with Swift 4.2 + Xcode 10

**Comment by pawanhopscotch** [comment]
> Same here, having trouble with Swift 4.2 + Xcode 10
> 
> EDIT: Whoops, somehow misconfigured the pod, working with minor adjustments now

may I know what configuration changes/ adjustments you have done?
