### ISSUE TITLE
revertAction not working after kolodaView?.swipe(.right)

### ISSUE THREAD

**Issue by rajesh-situ** [Yalantis/Koloda#393]
# Report

> The more information you provide, the faster we can help you.

⚠️ **report a bug**

###  What did you do?

> On button click I did  kolodaView?.swipe(.right) and on didSwipeCardAt index: Int method trying to do kolodaView.revertAction(direction: direction).

### What did you expect to happen?

> It should revert the prev kolodaView which is being swiped right.

### What happened instead?

> It dint revert the prev view. Point to be noted that this actions works fine when swipe the koloda cards however doesnt work when action added as button click.

### Your Environment

- Version of the component: _insert here_
- Swift version: 4
- iOS version: iOS 12
- Device: iPhone 8
- Xcode version: 10
- If you use Cocoapods: 1.5.3

**Comment by collramiro** [comment]
As a quick dirty fix you can use this:

`DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
                        self.kolodaView.revertAction()
                    }`

The issue is related to the animationSemaphore.

**Comment by rnkyr** [comment]
this is not possible due to (as mentioned) semaphore approach. you could try dispatching on the main thread without delays, but I'm not 100% sure it'll work

**Comment by Dfmarulanda** [comment]
Still happening.
