### ISSUE TITLE
background card's location

### ISSUE THREAD

**Issue by wixvii** [Yalantis/Koloda#398]
Hello, easy question, how can I set background card on top not bottom(default)?
I added image for what I want ?
![21233246-4864-11e5-9b64-e3c878daebf3](https://user-images.githubusercontent.com/17345325/48160814-e9a59380-e2e9-11e8-86cb-6f2f39afeb68.png)

**Comment by rnkyr** [comment]
hey, @wixvii!
now it's possible with changing `visibleCardsDirection`
