### ISSUE TITLE
Work with Objective-C?

### ISSUE THREAD

**Issue by mergesort** [Yalantis/Koloda#4]
I'd like to use this library in a project that's currently mostly Objective-C.

I integrate the project with Cocoapods, and the umbrella header seems to be empty, so none of the classes seem to be available to the Objective-C app. Would it be possible to annotate it in a way that allows for interoperability between the two languages?

It looks great, thanks a lot!

**Comment by AEugene** [comment]
There is no Objective-C support now, but we are going to add it in future versions.

**Comment by AEugene** [comment]
Now, you can use Objective-C branch
```ruby
use_frameworks!
pod "Koloda", :git => 'https://github.com/Yalantis/Koloda.git', :branch => 'objective-c_support'
```

**Comment by wang9262** [comment]
Hey,AEugene,Great work.I translate this swift style Koloda into ObjC style [Koloda-ObjC](https://github.com/wang9262/Koloda-ObjC).But you guys add the feature Objective-C support. Anyway thanks for the great work.

**Comment by fabiogomezdiaz** [comment]
@AEugene @wang9262 is there a sample usage guide for the objective-c_support branch in an Objective-C project? I looked at the examples and it was all Swift
