### ISSUE TITLE
Doesn't work with these constraints... 

### ISSUE THREAD

**Issue by RayanSaeed** [Yalantis/Koloda#40]
When I remove the bottom layout constraint and specify some specific Height for the Koloda View it works fine. But then it doesn't look good on all screen sizes. Can anybody suggest what the problem is?

Problem is with the swiping.. The cards show up but doesn't respond to any swipes

<img width="260" alt="screen shot 2015-09-21 at 12 57 32 pm" src="https://cloud.githubusercontent.com/assets/8598858/9987327/78f83d5e-6060-11e5-9fc2-9df265d21b57.png">

**Comment by AEugene** [comment]
I think it's question for stackoverflow.

**Comment by RayanSaeed** [comment]
@AEugene  No actually it's not.. Because i know AutoLayout quite well... The only problem here is that KolodaView is acting differently with different constraints... Do you get my point now?

**Comment by AEugene** [comment]
Actually, there are example and articles,  which explain koloda's layout. What you should look is method frameForCardAtIndex

**Comment by RayanSaeed** [comment]
And what I'm saying is that I'm fine with every thing related to frame... it's just that the functionality of the kolodaView ends.. It becomes static doesn't respond to any swipe or tap.... Are you getting my point now???

**Comment by AEugene** [comment]
https://gyazo.com/733d7594c18f09de6ecb49bce6163a2e
Tried different constraints. Same behaviour.

**Comment by RayanSaeed** [comment]
Let me check it... i'll tell you asap

**Comment by RayanSaeed** [comment]
@AEugene No still not working.. Why don't you try the constraints in the image above.. With the ViewController KolodaView... Not with the BackgroundAnimationViewController

Also note that i'm using the size class w:Compact h:Regular..... If that matters??

**Comment by AEugene** [comment]
@RayanSaeed  https://gyazo.com/3ffc5ffbc0b7136fc3f235dd46e9f4c5
Everything according to logic in frameForCardAtIndex method

**Comment by RayanSaeed** [comment]
@AEugene As I told you earlier.. The frame is fine with me also.. Everything is according to logic but the problem is with the KolodaView not responding to any Tap or Swipe... Should I create a repository of my project for you to have a look at??

**Comment by AEugene** [comment]
It's absolutely functional in the example project.

**Comment by RayanSaeed** [comment]
Perhaps it is... but can you please have a look at my project (link to repository)? Maybe you can find out what the problem is with my code in 5 minutes? Please

**Comment by RayanSaeed** [comment]
@AEugene  Please if you can have a look at this project here for 5 minutes...
https://github.com/RayanSaeed/Scrapster

**Comment by Kourghan** [comment]
@RayanSaeed project is empty.

**Comment by RayanSaeed** [comment]
@Kourghan As I mentioned in my last comment.. I'm currently updating the repository. So please wait for a few minutes.... Your help is highly appreciated thanks a lot....

**Comment by RayanSaeed** [comment]
@Kourghan Can you have a look at it now.. It's live now

**Comment by RayanSaeed** [comment]
@Kourghan It's live now.. Can you please have a look at it?

**Comment by Kourghan** [comment]
@RayanSaeed sorry, it's 404 error

**Comment by RayanSaeed** [comment]
@Kourghan When you are online and want to have a look at it.. Please comment here so that I make it live again.. I had to delete it because it contains some confidential information

**Comment by RayanSaeed** [comment]
@Kourghan Oh there you are live again

**Comment by RayanSaeed** [comment]
@Kourghan Here is the dropbox link... Please have a look at it.. Github is not working as expected right now for some reason...

**Comment by RayanSaeed** [comment]
@Kourghan Here is the dropbox link... Please have a look at it.. Github is not working as expected right now for some reason...
https://www.dropbox.com/s/xzl8n9qb6ggf4jo/Scrapster.zip?dl=0
