### ISSUE TITLE
A lot of issues with CocoaPods, starting with this one

### ISSUE THREAD

**Issue by carrasc0** [Yalantis/Koloda#400]
/Volumes/Almacen/iOS/Proyects/Mine/Flech/Pods/Koloda/Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift:326:25: Value of type '[CGLine]' (aka 'Array<(start: CGPoint, end: CGPoint)>') has no member 'compactMap'

Any suggestions? I tried with change Swift version to 3.2 and nothing happened :/

**Comment by rnkyr** [comment]
currently, Koloda has swift 4.2 as the primary version

if you need it for older swift version please consider using one of the [older](https://github.com/Yalantis/Koloda#release-notes) version of the library

you could also open a PR with introduced back compatibility for swift 3.2
