### ISSUE TITLE
Skips first two items in array

### ISSUE THREAD

**Issue by esteven1234** [Yalantis/Koloda#407]
# Report

###  What did you do?

> Loaded a standard array of objects as Koloda data source 

### What did you expect to happen?

> For the card stack to display array and index 0, 1, 2, and so on

### What happened instead?

> Using a simple print statement I noticed that objects at index 0 and 1 were being skipped through and not displayed at any point in the stack, I couldn't see a reason why this would happen, unless I'm misunderstanding the index system.

### Your Environment

- iOS version: 12

**Comment by rnkyr** [comment]
hey, @esteven1234
just checked the example project. I've printed index inside `koloda(_:viewForCardAt:)` method and it looks like it works just fine (e.g. printed 0, 1, 2, 3, and so on)

that should be something specific for your case or I simply misunderstood the problem. could you share some code?

**Comment by esteven1234** [comment]
I’ve realized my mistake, the first the cards are loaded simultaneously such that there are three Casio left cards in the stack and three cards are at all times visible. I simply put my iterating method in the wrong location such that may labels and the like we’re out of sync with the current card.

**Comment by rnkyr** [comment]
great! closing then

thank you for your feedback :)
