### ISSUE TITLE
Shows every card in the stack and throws error on swipe

### ISSUE THREAD

**Issue by draeceo** [Yalantis/Koloda#414]
The first call to load the view works fine, showing the normal three cards at a time and functioning properly. However when I subsequently load it after closing the app and loading the view, it shows every card all the way down to the bottom of the screen, and throws an error whenever a swipe is attempted.

**Comment by esteven1234** [comment]
I attempted to set the number of visible cards as well, to no avail

**Comment by esteven1234** [comment]
![img_1070](https://user-images.githubusercontent.com/39804124/52160500-419f2c80-2684-11e9-8149-7b734c902de7.PNG)

**Comment by den-zv** [comment]
Hey! Can you please provide a code example that causes the issue?

Looking on screenshot provided it seems there are a lot of `KolodaView`s on screen (but it supposed to be only one?).
