### ISSUE TITLE
Not make cards have a "stacked" look

### ISSUE THREAD

**Issue by HermanKayy** [Yalantis/Koloda#418]
Right now by default the cards will look like one is stacked on top of another from the bottom of the Koloda Card view. Is there a way to not show the next two cards on the bottom of the Koloda view and make it look "stacked"?

**Comment by den-zv** [comment]
Hey! Can you please provide some example image of how it should look like?

Also `KolodaView` has `visibleCardsDirection`, `backgroundCardsTopMargin`, `backgroundCardsScalePercent` properties, maybe you'll find them useful.

Something like:
```
kolodaView.visibleCardsDirection = .top
kolodaView.backgroundCardsTopMargin = 12.0
kolodaView.backgroundCardsScalePercent = 1.05
```

Closing this issue.
Please ping us back with more information in case problem is still there.
