### ISSUE TITLE
Animate Next Card 

### ISSUE THREAD

**Issue by HermanKayy** [Yalantis/Koloda#420]
Is there a way to animate next card when you set number of visible cards to 1? The default is 3 and when you swipe the next card will slowly expand. If you set the visibleCardsCount to 1, the next card doesn't have the animation anymore. Is there a way to still keep the animation?

**Comment by den-zv** [comment]
Hey! It's just the way `KolodaView` works - it shows last card after first one is disappeared. So you need at least 2 cards to see 2nd card's animation.

You can try something like this to make it look like there is only 1 card but actually have 2 cards on screen:
```
kolodaView.visibleCardsDirection = .top
kolodaView.backgroundCardsTopMargin = 0
kolodaView.backgroundCardsScalePercent = 0.9
kolodaView.countOfVisibleCards = 2
```

Closing this issue.
Please ping us back with more information in case problem is still there.
