### ISSUE TITLE
Pictures have a white filter making the pictures look extra white

### ISSUE THREAD

**Issue by Hsanka6** [Yalantis/Koloda#423]
# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What do you want to add?

> Please describe what you want to add to the component. 

### How should it look like?

> Please add images. 

## Report a bug
I attached pics above and I'm not sure why it's like this.

###  What did you do?
koloda view
<img width="1280" alt="Screen Shot 2019-04-01 at 11 30 07 PM" src="https://user-images.githubusercontent.com/5545840/55380928-95888f00-54d6-11e9-8ab5-5bc2264c4518.png">

custom view for koloda
<img width="1280" alt="Screen Shot 2019-04-01 at 11 30 15 PM" src="https://user-images.githubusercontent.com/5545840/55380938-9caf9d00-54d6-11e9-8bee-f6688660e064.png"

### What did you expect to happen?

I accepted to see original colors like the picture I attached.
Picture is supposed to look like this:
[https://s3-media1.fl.yelpcdn.com/bphoto/CEe6_jafjiw78DPwEUJe9A/o.jpg](url)

### What happened instead?

but it looks like this:
<img width="350" alt="Screen Shot 2019-04-01 at 11 26 32 PM" src="https://user-images.githubusercontent.com/5545840/55380891-7d187480-54d6-11e9-88ac-c485e077c57c.png">

### Your Environment

- Version of the component: _insert here_
- Swift version: Swift 4
- iOS version: Version 10.1 (SimulatorApp-877 CoreSimulator-581.2)
- Device: iphone xr simulator
- Xcode version: 10.1
- If you use Cocoapods: 

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 55fc9fdf323b1945c8b9be38baff54de9cbc3c8a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foodies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod ‘Poi’
  pod 'CDYelpFusionKit', '1.5.1'
#  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'Alamofire'
  pod "Koloda"
  pod "Kingfisher"
  # Pods for Foodies

  target 'FoodiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodiesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.
https://github.com/Hsanka6/FoodiesApp

**Comment by hemo87** [comment]
Your project doesn't seem complete?

But Ive noticed the same behaviour, when declaring the UIImageView for the cell outside of the viewForCard function. 
So its possible, you can move it back there it should work normally. Another quirk is it doesn't show the card stack nor animate properly.

**Comment by Hsanka6** [comment]
Thanks, @hemo87 that solved my issue
