### ISSUE TITLE
After using `revertAction()` kolodaSwipeThresholdRatioMargin resets to 0.5

### ISSUE THREAD

**Issue by t0milee** [Yalantis/Koloda#428]
###  What did you do?

I set the delegate method to the following and all is working until I use the `revertAction()` method, after that this has no effect and the value returns to 0.5
```swift
func kolodaSwipeThresholdRatioMargin(_ koloda: KolodaView) -> CGFloat? {
      return 0.3
}
```

### What did you expect to happen?

I'm expecting for it to always be 0.3

### What happened instead?

After revert action it's like it reverted to it's default value

### Your Environment

- Version of the component: 4.7
- Swift version: 4.2
- iOS version: 12.1.4
- Device: iPhone Xs
- Xcode version: 10.1 

### Project that demonstrates the bug

The bug can be easily reproduced in your demo project by just adding the code above `kolodaSwipeThresholdRatioMargin`

**Comment by edwardbeecroft** [comment]
Yep, I've just experienced this too.
