### ISSUE TITLE
PHImageManager async problem

### ISSUE THREAD

**Issue by unlu** [Yalantis/Koloda#430]
Trying to show photos from the photo gallery. I'm showing photos using PHImageManager. When I want to load photos async, photo quality is too bad.

When I change PHImageRequestOptions.isSynchronous = false. The quality is normal.

But I want to load photos async. What should I do?

**Comment by rnkyr** [comment]
This question is Photos related. It does nothing with Koloda itself

there're a bunch of ways to achieve your goal. try asking on stackoverflow
