### ISSUE TITLE
Error with cocoapods

### ISSUE THREAD

**Issue by wieseljonas** [Yalantis/Koloda#44]
I cannot fix this issue! I'me getting this error

`s/Mako/Pods/pop/pop/POP.h:27:9: Include of non-modular header inside framework module 'pop.POP'``
![image](https://cloud.githubusercontent.com/assets/1095469/10072555/eba21578-62c2-11e5-8783-55e0793604cb.png)

**Comment by AEugene** [comment]
1) Check that you have last stable version of Cocoapods(0.38.2)
2) Check that you added use_frameworks!
3) Clean and try to rebuild

**Comment by wieseljonas** [comment]
Hi @AEugene  It's working I was using the xcode beta, went back to the stable version and it works flowlessly!

**Comment by AEugene** [comment]
Glad to hear it. Thank your for response

**Comment by RayanSaeed** [comment]
Hi, I am getting the same error now. This happened to me after updating to Xcode 7.1
Right now I have the latest of everything, Xcode, OS X El Capitan and Cocoapods.. All of them are latest. What is the reason behind this? and how to fix it?

**Comment by wieseljonas** [comment]
Same as  @RayanSaeed

**Comment by RayanSaeed** [comment]
@wieseljonas  Other people are also facing the same issue with Xcode 7.1 with other pods like GoogleMaps, ReactiveCocoa etc... 

I hope someone can find a fix

**Comment by hilen** [comment]
@RayanSaeed take a look at here : https://github.com/facebook/pop/issues/285

**Comment by RayanSaeed** [comment]
@hilen Thanks buddy. I had fixed it already with that script provided by someone else in another issue here in Koloda repo. :)
