### ISSUE TITLE
Issue with swipe animation koloda View

### ISSUE THREAD

**Issue by osvinexperts** [Yalantis/Koloda#440]
# Report

> The more information you provide, the faster we can help you.

 **report a bug**. 

###  What do you want to add?
I am adding a simple swipe on button action, it was working fine with static data, but as soon as I load data from API, on swiping the card removes without swiping animation, it just goes off like blink though it works well when there is just one card left. I have seen your other open issue, but layoutDeck() solution did not work for me. Please guide me it is a very good library.

### How should it look like?
It should show the animation of swiping right and left

### What did you expect to happen?
it should just go off with animation, when I rewind, it comes back with animation.

### Your Environment

- Version of the component: Koloda 5.0
- Swift version: swift 4
- iOS version: ios 13
- Device: iPhone XR
- Xcode version: XCode 10
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by seropusha** [comment]
Need more details, code examples for reproduce this bug
Please make sure that you work with UI on `main` thread.

Issue will be closed.
