### ISSUE TITLE
Need to change drag percentage. 

### ISSUE THREAD

**Issue by AmandeepBIT** [Yalantis/Koloda#441]
If user just drag 20% of the card then card should be dragged. Let me know how its possible........Thanks in advance

**Comment by seropusha** [comment]
Dear @AmandeepBIT you should implement method 
`func kolodaSwipeThresholdRatioMargin(_ koloda: KolodaView) -> CGFloat?` from `KolodaViewDelegate` and return value `0.0...1.0` it will be target percentage for complete draging of card.


Default value is `1.0` if return `0.2` you achieve needed result.
Issue will be closed.
