### ISSUE TITLE
Is this code still being maintained?

### ISSUE THREAD

**Issue by tsheaff** [Yalantis/Koloda#443]
We're considering using Koloda in our project. However, we see that it's not been updated at all in quite a long time, and most of the code is several years old.

Is this pod still being actively maintained?

**Comment by brownsoo** [comment]
maybe author is busy... I used own Koloda forked.

**Comment by seropusha** [comment]
Dear @tsheaff 

We are looking after of `Koloda` but there’s not always time to answer on issues. 
`Koloda` works properly on the latest version Swift 5.2.

If you need some customisation you can always make fork.

Thank you!
Issue will be closed.

**Comment by tsheaff** [comment]
Thanks @seropusha yes it's working greatforus, just curious on if it's officially maintained. For example, a new swift or iOS comes out, will it be updated to work properly or should we expect to fork and make those changes ourselves.

Appreciate your response.
