### ISSUE TITLE
Swipe Down on a card

### ISSUE THREAD

**Issue by RayanSaeed** [Yalantis/Koloda#45]
Hello, 

I shall really appreciate if you can just guide me a little on how can I modify the code in DraggableCardView.swift to add a downwards swipe also.. with all delegate callbacks and overlay etc?

Thanks

Never mind. I actually figured it out myself. Wish I could delete an issue.

**Comment by RayanSaeed** [comment]
I've actually made everything else work according to my requirements.. but it's just this function here for the overlay.. How do I go about calculating the percent so that I can differentiate between .Left .Right .Down
Should I add another var for this purpose or is there any other workaround?


<img width="1046" alt="screen shot 2015-09-29 at 5 03 03 pm" src="https://cloud.githubusercontent.com/assets/8598858/10163379/fb304fe8-66cb-11e5-9488-14dde2045d67.png">

**Comment by Liampronan** [comment]
I'm working on something similar so thought I'd add a gist for others' reference: https://gist.github.com/Liampronan/61f62d38183e4b217393#file-gistfile1-swift-L229

My approach:

1) modify swipeMadeAction() to accept UIPanGestureRecognizer as a param        swipeMadeAction(gestureRecognizer: UIPanGestureRecognizer) 
2) add  handleYSwipe(gestureRecognizer) to swipeMadeAction
3) create handleYSwipe(gestureRecognizer: UIPanGestureRecognizer) and modify to your needs in terms of yMagnitude

Any questions, let me know.

Thanks @AEugene and everyone else for the awesome repo!
