### ISSUE TITLE
How can I control Drag sensitiveness?

### ISSUE THREAD

**Issue by tigermobiledev** [Yalantis/Koloda#453]
Hi, Thanks for your this library.

Would it be possible to make the pan gesture on the cards a bit more sensitive?

Right now i need to swipe a little too hard to pass on to the next one.

Regards.

**Comment by MasahiroToyooka** [comment]
Koloda's API have kolodaSwipeThresholdRatioMargin(_:) method for that purpose.

**Comment by tigermobiledev** [comment]
@MasahiroToyooka , It works well, Thanks for your helping.
