### ISSUE TITLE
Programmatically create KolodaView

### ISSUE THREAD

**Issue by aemengo** [Yalantis/Koloda#47]
My team is trying to use the library and having trouble creating the required views programmatically (we try to avoid using the storyboard). However, we are having trouble calling the designated initializers of our `KolodaView` subclass. Is the normal workflow to have your views pre-made in storyboard or nib?

```swift
    override init(frame: CGRect) {
        super.init(frame)
    }
```

^Gives an compile error.

**Comment by AEugene** [comment]
Fixed with #48
