### ISSUE TITLE
How to hide elements for background animation

### ISSUE THREAD

**Issue by weyert** [Yalantis/Koloda#49]
I have been looking at the demo application and their you animate the next card into the background. I was wondering if it's possible to do this but in the meantime hide some elements of this card while this animation happens.

I am having a card similar to one in your demo. Only I am having some text in the top left corner of the card which is now being shown in the background. I prefer to hide all the textual elements and only show the background image.

What's the easiest approach to do this?

**Comment by weyert** [comment]
Anyone? :)

**Comment by AEugene** [comment]
Hi, @weyert 
In delegate method:
```swift
func kolodaDidSwipedCardAtIndex(koloda: KolodaView,index: UInt, direction: SwipeResultDirection)
```
You can get next card with ```koloda.viewForCardAtIndex(index: koloda.currentCardNumber) ``` and apply animation to it.

**Comment by weyert** [comment]
Ah okay, let's try that. Thank you. Guess, I can make a method like configureForBackgroundAnim so that it hides some UI elements.

**Comment by AEugene** [comment]
Tell us about the results
