### ISSUE TITLE
Allow Going "Backwards"

### ISSUE THREAD

**Issue by davecom** [Yalantis/Koloda#5]
I have a use case where I am using Koloda to show a series of graphs.  In this instance we would like swiping right to go to the "next" graph and swiping left to go to the "previous" graph.  The current behavior is that swiping in either direction goes to the next graph.  Is there a current workaround?

**Comment by AEugene** [comment]
Currently Koloda's behaviour on swiping is only going forward, but you can go backward if you apply "revert action". It's possible, that we will add this feature in future versions.

**Comment by davecom** [comment]
Thanks for the reply.  So, my workaround for now strategy might be to call revert action twice from kolodaDidSwipedCardAtIndex when a left swipe occurs?

**Comment by AEugene** [comment]
For now the solution is to create smart data source. For example, you load 10 cards and 3 of these are visible. The first card is configured as graph and others are configured as placeholders. When you swipe, your data source replaces next card placeholder to actual card (previous or next) and reloads Koloda. So for this feature you need 2 data sources(one manages Koloda, and second one stores your graphs).
