### ISSUE TITLE
Why networking_example project can't be compiled 

### ISSUE THREAD

**Issue by AladinWay** [Yalantis/Koloda#53]
First, I want to thank you very much for this great library. Actually Yalantis has only great and fancy libraries in Github. Keep going on and keep sharing with us please.

I want to try the networking example project but it does not compile with xcode 7.0.0 iOS9 maybe it's because of swift 2 ?

Also is there any chance that somebody can share an example with Parse.com and Facebook login ?

**Comment by AEugene** [comment]
@AladinWay Thank you for noticing. I've updated the branch.
