### ISSUE TITLE
Include of non-modular header inside framework module

### ISSUE THREAD

**Issue by zeronoun** [Yalantis/Koloda#56]
This error seems to have popped up again. Cocoapods is up to date, and this is an attempt to compile the included Example from a fresh download of the Koloda Master. 

![untitled](https://cloud.githubusercontent.com/assets/3847923/10697115/1c86053e-795f-11e5-94e7-e9f870e4b68f.jpg)

*Strangely, this error does not occur when compiling in Xcode 7.1 Beta 3 (7B60), only in Xcode 7.1 Stable (7B91b).*

**Comment by RayanSaeed** [comment]
Same here

**Comment by grimabe** [comment]
+1 Under Version 7.1 (7B91b) possibly due tu Swift 2.1 ?

**Comment by grimabe** [comment]
duplication of #55

**Comment by AEugene** [comment]
Issue will be fixed with CocoaPods/CocoaPods#4420
