### ISSUE TITLE
Glitch on iPhone 4s while dragging 

### ISSUE THREAD

**Issue by AladinWay** [Yalantis/Koloda#64]
Watch in HD and notice the glichs on the right of the card
https://www.youtube.com/watch?v=ZpKAbLb3spE&feature=youtu.be

**Comment by sebastianludwig** [comment]
Just to confirm: this is an issue with #60?

**Comment by sebastianludwig** [comment]
After checking out the [example project](http://www88.zippyshare.com/v/kPj7eBlb/file.html) provided by AladinWay, this is an issue with the current version of Koloda, not PR #60.

**Comment by AladinWay** [comment]
@sebastianludwig  I have tested your "Koloda-fix_distortion" branch and had the same issue

**Comment by sebastianludwig** [comment]
Thank you for clarifying! I'll try to get my hands on an iPhone 4S iOS 9.
