### ISSUE TITLE
Calling revertAction() inside kolodaDidSwipe causes bug

### ISSUE THREAD

**Issue by anilgoktas** [Yalantis/Koloda#65]
Hi, thank you for this awesome view.

I’m working on a project that requires to push cardViewController after selecting a card (swiping to right)

However user should be able to see selected card after popped cardViewController from navigation stack. Therefore I’ve added “revertAction()” inside “didSwipedCard()” delegate.

Here we go with an example;

+ `dataSource.count=2 and visibleCards=1` (one card swiped, so last card is visible)

+ Swipe the last card to right

```Swift
kolodaDidSwipedCard() {
	if direction == .Right {
		// Breakpoint
		kolodaView.revertAction()
		performSegue()
	}
}
```

+ Let’s look before breakpoint;

```Swift
swipedAction() got called and processed this lines {
	animating = true
	visibleCards.removeAtIndex(0) // -> visibleCards.count = 0

	// -> visibleCards.isEmpty = true
	if !visibleCards.isEmpty {
		<# code #>
	} else {
		delegate?.kolodaDidSwipedCardAtIndex(self, index: UInt(currentCardNumber - 1), direction: direction)
		animating = false
		self.delegate?.kolodaDidRunOutOfCards(self)
	}
}
```

so at this point `kolodaView.animating = true`

+ After breakpoint

```Swift
revertAction got called {
	// animating = true -> revertAction doesn’t work
	if currentCardNumber > 0 && animating == false {
		<# revertAction code #>
	}
}
```
Because of revertAction didn't work, selected card hasn't showed up, kolodaView has no visible cards.

+ Solution

Change order of the lines at swipedAction()

```Swift
swipedAction() {
	…
	if !visibleCards.isEmpty {
		<# code #>
	} else {
		animating = false // before delegate method
		delegate?.kolodaDidSwipedCardAtIndex(self, index: UInt(currentCardNumber - 1), direction: direction)

		// Check if visibleCards is still empty after delegate method
		if visibleCards.isEmpty {
			delegate?.kolodaDidRunOutOfCards(self)
		}
	}
}
```

Again, thanks for your hard work.

**Comment by AEugene** [comment]
Hi @anilgoktas , We'll look into this issue after holidays. Thank you for contribution.

**Comment by AndrewiOS** [comment]
@anilgoktas Please check the last version of Koloda. This bug is fixed
