### ISSUE TITLE
Duplicate calls when swiping quick

### ISSUE THREAD

**Issue by lunswor** [Yalantis/Koloda#73]
When loading cards with data (i'm loading around 50 at a time), if you swipe quickly through them, i am getting duplicate calls to kolodaDidSwipedCardAtIndex with the same index which then ends up freezing the app. I then end up seeing the top two cards with a slight transparency to see the card underneath.

**Comment by AEugene** [comment]
Hi @lunswor . Which version of Koloda do you use?

**Comment by AEugene** [comment]
I've tried fast swiping with this PR #71 . It seems like issue is fixed.

**Comment by lunswor** [comment]
Yep it seems fixed. Thanks :)
