### ISSUE TITLE
Custom Views in cards

### ISSUE THREAD

**Issue by beatscode** [Yalantis/Koloda#74]
What do I need to do to get a custom view in the right dimensions of each card?

```
    func kolodaViewForCardAtIndex(koloda: KolodaView, index: UInt) -> UIView {
        let vc:KolodaViewController = self.storyboard?.instantiateViewControllerWithIdentifier("kolodaviewcontroller") as! KolodaViewController
      
        let tmpUser:user = users[Int(index)]
        vc.profileImageURL = tmpUser.imageURL
        vc.name = tmpUser.name
        vc.bio = tmpUser.bio
        url = tmpUser.trackURL
        
        //return UIImageView(image: nil)
        return vc.view
    }
```

I created a view controller with some elements arranged the way I'd like to see it in the card.
![b9638a9b-8822-4f31-abee-48d2ad4bc181](https://cloud.githubusercontent.com/assets/1777648/11427368/4bc56ede-9430-11e5-86bc-3d0df2033f58.png)

Running the code presents the following.

![223a9843-84ca-46be-b7e5-390aacff5dcd](https://cloud.githubusercontent.com/assets/1777648/11427500/3dfe45c2-9431-11e5-8bb8-aa0102712c0f.png)

**Comment by AEugene** [comment]
hi @beatscode . Firstly, you've forgotten these methods:
```swift
addChildViewController(vc)
//Your code
controller.didMoveToParentViewController(vc)
```
Than try
```swift
vc.view.translatesAutoresizingMaskIntoConstraints = false
```

**Comment by beatscode** [comment]
I was able to customize the layout constraints in a custom view controller to get the layout i wanted. However when testing it out on the iPad its not adjusting properly.

![b58ae640-2f0a-4d93-90f0-cf7b2fcc1d18](https://cloud.githubusercontent.com/assets/1777648/11735175/60a13a88-9f8c-11e5-87eb-568ca131f397.png)


Ipad

![5713454d-322a-43a2-bb47-8df8b51b3574](https://cloud.githubusercontent.com/assets/1777648/11735182/6f891502-9f8c-11e5-96cb-46260d3b8ce4.png)


I tried implementing what you added above but I'm not quite sure I'm doing this right. There wasn't much of a visual difference. What am i doing wrong?

**Comment by beatscode** [comment]
Still a newb at using auto layout + size classes. Your code actually did work in conjunction with fixing auto layout issues. 
Thank you

**Comment by AEugene** [comment]
@beatscode Glad to hear that you solved your issue.

**Comment by ArunmiOS** [comment]
Is it possible to add in storyboard?i need to add multiple viewcontroller as cardView?please let me know if possible and how to achieve it

**Comment by AEugene** [comment]
@ArunmiOS I don't think so.

**Comment by ethan021021** [comment]
Hi. Im currently having a similar issue to exactly what OP was getting. Was there a fix that went out for this?
