### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by RayanSaeed** [Yalantis/Koloda#79]
After doing 
```
pod update
```
I get this error when I try to build the project:
```
Command failed due to signal: Segmentation fault: 11
```

So I tried to downgrade to Koloda => 2.0.4 and it all worked fine, can anybody tell what's causing this problem?

**Comment by migfabio** [comment]
Same error! +1

**Comment by migfabio** [comment]
@RayanSaeed I figured out...
They renamed KolodaViewDataSource and KolodaViewDelegate methods. 
Make sure that your class has correct methods implemented

**Comment by RayanSaeed** [comment]
hmm okay, let me see. I'll update this comment if get any success.

**Comment by AEugene** [comment]
hi @RayanSaeed , Sorry for that we'll add changelog in future.
