### ISSUE TITLE
Currently visible card never has correct frame height

### ISSUE THREAD

**Issue by mitchellporter** [Yalantis/Koloda#81]
First off, just wanted to say thanks for putting this awesome repo together. I'm using the defaults that come with `KolodaView` and one thing I've noticed is that if `backgroundCardsTopMargin` is set to anything other than zero, then the visible card never has the correct frame.

When using the `backgroundCardsTopMargin` default of `4` that comes with `KolodaView`, my card has a height of `307` instead of the correct value I have set which is `315`. 

I love the visual effect that you can achieve by using `backgroundCardsTopMargin`, it's really cool being able to see a little bit of the cards that are behind the currently visible one, but at the same time we cannot allow this to actually modify the visible card's frame height.

Can we try and find a way to still allow for the same visual effect but keep the correct frame height for the visible card?

**Comment by AEugene** [comment]
Hi @mitchellporter . When I developed Koloda I had two choices:
1) Layout all cards inside KolodaView.
2) Layout first card with frame of KolodaView and let background cards go out of KolodaView's bounds.
I prefer 1st option. However as noted in README:
```swift
    public func frameForCardAtIndex(index: UInt) -> CGRect 
```
This method is responsible for card frames calculation. So you may take this method inside KolodaView class as default implementation(just like flow layout for UICollectionView) and override it for your needs.
