### ISSUE TITLE
Delegate method for when user "releases" card back to starting position?

### ISSUE THREAD

**Issue by royherma** [Yalantis/Koloda#83]
Wasn't able to find this, but have a feeling I can get it somehow -

Using the "draggedCardWithFinishPercent" function to make some opacity animation that is relative to the percent of completion, but when the user lifts his finger from the card and it pops back to its original spot, I have no way of knowing and thus cannot revert the opacity animation back to normal as well. This only works if the users drags back the card manually to its starting position, or if they swipe in one of the directions and get the card of the screen.

Any ideas?

Thanks! (Love your stuff)

**Comment by YongmingLee** [comment]
You may override function like:
 func koloda(kolodaDidResetCard koloda: KolodaView)
{
 ...
}

**Comment by AEugene** [comment]
@royherma I've updated readme. Now we have next delegate method:
```swift
func koloda(kolodaDidResetCard koloda: KolodaView)
```
