### ISSUE TITLE
Implement ability to add more cards to deck without reloading current one

### ISSUE THREAD

**Issue by numen31337** [Yalantis/Koloda#84]
Issue:
When you trying to add more cards to deck you forced to use reloadData() method, but this flow also reloading current presented card, for card which have some states or kinda interactive this case is unacceptable.

Possible solutions:
I haven't investigated this issue deeply yet but looks like reconfigureCards() should start from 1 instead of 0 for calls from loadMissingCards() to achieve that.
Looks like dedicated method to add more fetched items to deck is needed because you should expect reloadData() to reload everything

**Comment by AEugene** [comment]
Hi @numen31337 , We're thinking about implementation of updates handling similar to UITableView. We may implement it in future versions. Thank you for noticing the issue.

**Comment by pnicholls** [comment]
Super interested in this feature as well.

@AEugene if you explain a little more about what you are thinking in terms of implementation ill try to get  a PR together.
