### ISSUE TITLE
Are we meant to subclass DraggableCardView?

### ISSUE THREAD

**Issue by CharlesW95** [Yalantis/Koloda#91]
1. I noticed most of the init methods in DraggableCardView aren’t public, which makes it difficult to subclass it (to make custom cards) since we can’t call the designated init function on super.init. Are we not meant to subclass DraggableCardView, or should we go ahead and change the required variables and methods to public?

2. Also, on a test run, when I returned a standard UIView instance in the viewForCardAtIndex protocol function, the background card animation seemed to work fine, but the background cards stopped moving if I tried to pass it an instance of DraggableCardView. So

let view = DraggableCardView()

doesn't work,

but let view = UIView()

seems to work just fine.

Thank you for your help.

**Comment by AEugene** [comment]
Hi @CharlesW95 . Short answer is no, you don't need to return subclass of DraggableCardView in data source method.
As you can see from the implementation: Koloda sends the view it received from viewForCardAtIndex to DraggableCardView, and then DraggableCardView configures itself with view from data source(adds it as subview, setups constraints, etc).
