### ISSUE TITLE
Create a swipe Infinite. 

### ISSUE THREAD

**Issue by yaya272** [Yalantis/Koloda#98]
I want to create an endless swipe feed using Koloda. I want to initially load 10 cards from the database. Then after swiping 5 cards, I load 5 more and so on. How can I implement this?

**Comment by migfabio** [comment]
Hi @yaya272 

I did the same thing in this way. In 

```swift
func koloda(koloda: KolodaView, didSwipedCardAtIndex index: UInt, inDirection direction: SwipeResultDirection)
```
I just wrote

```swift
if (koloda.currentCardNumber + 5) % 10 == 0 {
	prefetch()
}
```
```swift
prefetch()
```

is just my method to load data from database or wherever you want and works like this

```swift
if results != nil { // results from database
    if items.count >= 5 { //items is the array used by koloda
        items.removeFirst(5)
    }
    items.appendContentsOf(results)
    cardView.resetCurrentCardNumber() //cardView is a custom class that extends KolodaView
}
```

**Comment by yaya272** [comment]
HI @migfabio
I actually tried a similar thing before but the problem I'm having is the reset animation after resetCurrentCardNumber is called. The whole thing reloads. I don't want that. Do you know how to eliminate that?

Thanks a lot

**Comment by migfabio** [comment]
@yaya272 yeah, i know what you mean, but i can't find a workaround for this, sorry.
luckily in my project there isn't this requirement (animation when show/reload cards)

**Comment by lukas2** [comment]
I solved it like this.

In my data source, in delegate-method ```func koloda(koloda: KolodaView, didSwipedCardAtIndex index: UInt, inDirection direction: SwipeResultDirection)```I check if count of cards is smaller than some number and if not, I trigger an update. It looks something like this:

        if (myCards.count - Int(index)) < 10 {
            // load more cards if there's less than 10 left to show
            update()
        }

However, ```KolodaView``` does not know I did this, and therefore it will still run out of cards and call its reload method. (This happens in KolodaView.swift method ```private func swipedAction(direction: SwipeResultDirection)```.) 

In that method the variable ```cardCount``` still has an old value and the check

        if shownCardsCount - 1 < countOfCards { .... }

will be false, and ```dataSource.koloda(self, viewForCardAtIndex: UInt(shownCardsCount - 1))``` will not be called for the last 3 cards, and we run out of cards.

So in our project I added a way to let KolodaView know that it should ask me for the right number of cards again. Here's the commit:

https://github.com/lukas2/Koloda/commit/977b8d2ed87aa2691ae264b315c940658d097abc

I also made it into a pull request, in case you think it's useful: https://github.com/Yalantis/Koloda/pull/104

(If anyone solved infinite swipe differently, I'd like to hear it!)

**Comment by lukas2** [comment]
Update, I found a better fix: https://github.com/Yalantis/Koloda/pull/105

I think it's enough to call existing KolodaView method ```reloadData()``` if ```countOfCards``` is updated there. So same idea, except we don't need an extra method.

**Comment by tomekh7** [comment]
@yaya272 there is delegate method `koloda(kolodaShouldApplyAppearAnimation koloda: KolodaView) -> Bool` and if you return false appear animation shouldn't be applied on reloading. So after fetching next bunch of data you should return false in this method. Hope this solves your problem.
